// dsh-desktop-session-manager client bundle — GENERATED by scripts/lib/build-client-bundle.mjs, do not edit.
// Modular source lives in src/; this file is the deployed artifact.
window.__ModuleLoader__.load({
	id: "dsh-desktop-session-manager",
	factory: (require) => {
		var __modules = {
"./contract.js": function (require, module, exports) {
// dsh-desktop-session-manager — client half of the wire contract.
// Mirror of the host plugin's lib/contract.js; keep both files in sync.
module.exports = {
  BASE_PATH: '/desktop-sessions',
  CODES: {
    // Target session has work in flight (or could not be released from the
    // host store). Archived sessions only attached but idle are released
    // and deleted instead of refused.
    LIVE: 'live',
    UNKNOWN: 'unknown',
    DEGRADED: 'degraded',
  },
}

},
"./api.js": function (require, module, exports) {
// dsh-desktop-session-manager — same-origin HTTP client for the host API.
const { BASE_PATH } = require('./contract.js')

/** Normalized failure carrying the host's stable code (see contract.js). */
class ApiError extends Error {
  constructor(code, message) {
    super(message)
    this.name = 'ApiError'
    this.code = code ?? 'error'
  }
}

async function request(path, options) {
  let resp
  try {
    resp = await fetch(`${BASE_PATH}${path}`, {
      headers: { 'content-type': 'application/json' },
      cache: 'no-store',
      ...options,
    })
  } catch (error) {
    throw new ApiError('network', `无法连接会话管理服务: ${error?.message ?? error}`)
  }
  let payload = null
  try {
    payload = await resp.json()
  } catch {
    /* non-JSON body */
  }
  if (!resp.ok || payload?.ok === false) {
    throw new ApiError(payload?.code ?? 'http', payload?.error ?? `请求失败 (HTTP ${resp.status})`)
  }
  return payload ?? { ok: true }
}

/** @returns {Promise<{ok:boolean, sessions:Array}>} */
function listSessions() {
  return request('/list')
}

/** @returns {Promise<{ok:boolean}>} */
function deleteSession(id) {
  return request('/delete', { method: 'POST', body: JSON.stringify({ id }) })
}

/** @returns {Promise<{ok:boolean}>} */
function unarchiveSession(id) {
  return request('/unarchive', { method: 'POST', body: JSON.stringify({ id }) })
}

module.exports = { ApiError, listSessions, deleteSession, unarchiveSession }

},
"./locales.js": function (require, module, exports) {
// dsh-desktop-session-manager — dictionary namespace `sessionManager`.
// Simplified Chinese is the key-set source of truth; English mirrors it.
const zh = {
  'nav': '会话管理',
  'title': '会话管理',
  'intro': '共 {count} 个会话 · {archived} 个已归档。归档会话可恢复到工作区列表；删除将永久移除会话及其全部消息记录。',
  'group.archived': '已归档',
  'group.all': '全部会话',
  'group.archived.none': '没有归档的会话',
  'group.all.none': '暂无会话',
  'loading': '正在加载会话…',
  'error.load': '加载会话列表失败：{error}',
  'row.current': '当前',
  'row.restore': '恢复',
  'row.delete': '删除',
  'row.meta.tokens': '{tokens} tokens',
  'row.meta.turns': '{count} 轮',
  'row.meta.untitled': '(未命名会话)',
  'row.meta.noDate': '时间未知',
  'status.deleted': '会话已删除',
  'status.restored': '会话已恢复到列表',
  'confirm.title': '删除会话？',
  'confirm.desc': '将永久删除“{title}”及其全部消息记录，此操作不可恢复。',
  'confirm.ok': '删除',
  'confirm.cancel': '取消',
  'confirm.busy': '正在删除…',
  'capNote': '仅显示最近 {limit} 个会话',
};

const en = {
  'nav': 'Session Manager',
  'title': 'Session Manager',
  'intro': '{count} sessions · {archived} archived. Archived sessions can be restored to the workspace list; deleting permanently removes a session and all of its messages.',
  'group.archived': 'Archived',
  'group.all': 'All sessions',
  'group.archived.none': 'No archived sessions',
  'group.all.none': 'No sessions yet',
  'loading': 'Loading sessions…',
  'error.load': 'Failed to load sessions: {error}',
  'row.current': 'Current',
  'row.restore': 'Restore',
  'row.delete': 'Delete',
  'row.meta.tokens': '{tokens} tokens',
  'row.meta.turns': '{count} turns',
  'row.meta.untitled': '(untitled session)',
  'row.meta.noDate': 'unknown time',
  'status.deleted': 'Session deleted',
  'status.restored': 'Session restored to the list',
  'confirm.title': 'Delete session?',
  'confirm.desc': 'This permanently deletes “{title}” and all of its messages. This cannot be undone.',
  'confirm.ok': 'Delete',
  'confirm.cancel': 'Cancel',
  'confirm.busy': 'Deleting…',
  'capNote': 'Showing the latest {limit} sessions',
};

module.exports = { zh, en };

},
"./use-session-manager.js": function (require, module, exports) {
// dsh-desktop-session-manager — list state + actions hook.
const { useCallback, useEffect, useMemo, useState, useSyncExternalStore } = require('react')
const api = require('./api.js')

const noopSub = () => () => {}

/**
 * Overlay the live archive set onto server rows. The host endpoint marks
 * archived rows too, but the client runtime's workspaces store is the live
 * source the sidebar itself uses (updated by host events), so merging here
 * keeps the section in sync with archive actions from anywhere — and makes
 * the section correct even against a host that under-reports the flag.
 * @param rows - session rows (server shape, `archived` respected).
 * @param archivedIds - live archive id list from the workspaces store.
 * @returns rows with the merged `archived` flag.
 */
function mergeArchivedFlags(rows, archivedIds) {
  if (!Array.isArray(archivedIds) || archivedIds.length === 0) return rows
  const set = new Set(archivedIds)
  return rows.map((row) => (set.has(row.id) && row.archived !== true ? { ...row, archived: true } : row))
}

/**
 * Loads the host session list and owns delete/unarchive actions with
 * optimistic local updates. One busy action at a time (busyId). The
 * `workspaces` client service (when present) contributes the live archive
 * set merged on top of the server rows.
 */
function useSessionManager(workspaces) {
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [busyId, setBusyId] = useState(null)
  const [notice, setNotice] = useState(null)

  const refresh = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const result = await api.listSessions()
      setSessions(result.sessions ?? [])
    } catch (err) {
      setError(err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  const workspaceSnap = useSyncExternalStore(
    (fn) => (workspaces?.list?.subscribe ?? noopSub)(fn),
    () => workspaces?.list?.getSnapshot?.() ?? null,
    () => null,
  )
  const archivedIds = workspaceSnap?.archivedSessionIds ?? null
  const rows = useMemo(
    () => (archivedIds === null ? sessions : mergeArchivedFlags(sessions, archivedIds)),
    [sessions, archivedIds],
  )

  const clearNotice = useCallback(() => {
    setNotice(null)
  }, [])

  const remove = useCallback(async (id) => {
    setBusyId(id)
    setError(null)
    try {
      await api.deleteSession(id)
      setSessions((list) => list.filter((row) => row.id !== id))
      setNotice({ kind: 'deleted' })
      return true
    } catch (err) {
      setError(err)
      return false
    } finally {
      setBusyId(null)
    }
  }, [])

  const unarchive = useCallback(async (id) => {
    setBusyId(id)
    setError(null)
    try {
      await api.unarchiveSession(id)
      setSessions((list) => list.map((row) => (row.id === id ? { ...row, archived: false } : row)))
      setNotice({ kind: 'restored' })
      return true
    } catch (err) {
      setError(err)
      return false
    } finally {
      setBusyId(null)
    }
  }, [])

  const archivedCount = rows.reduce((n, row) => n + (row.archived ? 1 : 0), 0)

  return { sessions: rows, loading, error, busyId, notice, archivedCount, refresh, remove, unarchive, clearNotice }
}

module.exports = { useSessionManager, mergeArchivedFlags }

},
"./styles.js": function (require, module, exports) {
// dsh-desktop-session-manager — settings-section stylesheet.
//
// Visual language mirrors the existing settings sections (ui-settings-models
// ModelsSection.module.css): same section geometry, row cards, tags, pill
// buttons and confirm-dialog chroma, so the page reads as native settings UI.
const css = `
.smx_section{max-width:720px;color:var(--dsw-alias-label-primary);flex-direction:column;gap:12px;display:flex}
.smx_title{color:var(--dsw-alias-label-primary);margin:0;font-size:16px;font-weight:500;line-height:24px}
.smx_intro{color:var(--dsw-alias-label-tertiary);margin:0;font-size:14px;line-height:22px}
.smx_notice{color:var(--dsw-alias-state-warn-label);margin:0;font-size:12px;line-height:18px}
.smx_error{color:var(--dsw-alias-state-error-primary);margin:0;font-size:12px;line-height:18px}
.smx_savedNotice{color:var(--dsw-alias-state-success-primary);margin:0;font-size:12px;line-height:18px}
.smx_groupTitle{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;text-transform:uppercase;letter-spacing:.4px;margin:14px 2px 6px}
.smx_rows{flex-direction:column;gap:8px;margin:0;padding:0;list-style:none;display:flex}
.smx_rowCard{border:1px solid var(--dsw-alias-border-l2);border-radius:12px;flex-direction:column;gap:8px;padding:12px 14px;display:flex}
.smx_rowHead{align-items:center;gap:10px;display:flex}
.smx_rowIdentity{align-items:center;gap:6px;min-width:0;display:inline-flex}
.smx_rowName{color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer;background:0 0;border:none;padding:0;font-size:14px;font-weight:500;line-height:22px;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left}
.smx_rowName:hover{text-decoration:underline}
.smx_rowTag{border:1px solid var(--dsw-alias-border-l3);color:var(--dsw-alias-label-secondary);border-radius:4px;flex:none;padding:1px 6px;font-size:11px;line-height:16px}
.smx_rowMeta{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.smx_rowActions{align-items:center;gap:4px;margin-left:auto;flex:none;display:inline-flex}
.smx_secondaryButton{box-sizing:border-box;height:28px;color:var(--dsw-alias-label-secondary);font:inherit;cursor:pointer;background:0 0;border:none;border-radius:14px;justify-content:center;align-items:center;padding:0 10px;font-size:12px;line-height:18px;display:inline-flex}
.smx_secondaryButton:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-solid)}
.smx_dangerButton{box-sizing:border-box;height:28px;color:var(--dsw-alias-state-error-primary);font:inherit;cursor:pointer;background:0 0;border:none;border-radius:14px;justify-content:center;align-items:center;padding:0 10px;font-size:12px;line-height:18px;display:inline-flex}
.smx_dangerButton:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-danger)}
.smx_secondaryButton:disabled,.smx_dangerButton:disabled{opacity:.4;cursor:default}
.smx_footerButton{box-sizing:border-box;height:36px;font:inherit;cursor:pointer;border:none;border-radius:18px;justify-content:center;align-items:center;padding:0 14px;font-size:14px;line-height:22px;display:inline-flex}
.smx_footerCancel{color:var(--dsw-alias-label-secondary);background:0 0}
.smx_footerCancel:hover{background:var(--dsw-alias-interactive-bg-hover-solid)}
.smx_footerDanger{background:var(--dsw-alias-state-error-primary);color:#fff}
.smx_footerDanger:hover:not(:disabled){filter:brightness(1.08)}
.smx_footerButton:disabled{opacity:.4;cursor:default}
`;

const TAG_ID = '@deepseek-ai/dsh-desktop-session-manager/section.css';

/** Install the stylesheet exactly once per document. */
function ensureStyles() {
  if (typeof document === 'undefined') return;
  if (document.querySelector(`style[data-plugin-css=${JSON.stringify(TAG_ID)}]`) !== null) return;
  const tag = document.createElement('style');
  tag.dataset.plugin = 'dsh-desktop-session-manager';
  tag.dataset.pluginCss = TAG_ID;
  tag.textContent = css;
  document.head.appendChild(tag);
}

module.exports = { ensureStyles };

},
"./message.js": function (require, module, exports) {
const ROOT_ID = 'dsh-desktop-message-root';
function showMessage(text) {
  if (typeof document === 'undefined' || text == null || text === '') return;
  let root = document.getElementById(ROOT_ID);
  if (root === null) { root = document.createElement('div'); root.id = ROOT_ID; root.className = 'dsh_messageRoot'; root.setAttribute('aria-live', 'polite'); document.body.appendChild(root); }
  if (document.getElementById('dsh-desktop-message-style') === null) { const style = document.createElement('style'); style.id = 'dsh-desktop-message-style'; style.textContent = '.dsh_messageRoot{position:fixed;z-index:10000;top:20px;left:50%;width:min(420px,calc(100vw - 32px));pointer-events:none;transform:translateX(-50%);display:flex;flex-direction:column;gap:10px}.dsh_message{box-sizing:border-box;min-height:40px;padding:10px 12px;border:1px solid var(--dsw-alias-state-error-primary,#f56c6c);border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#303133);box-shadow:0 8px 24px rgba(0,0,0,.14);font-size:13px;line-height:20px;pointer-events:auto;display:flex;gap:8px}.dsh_messageText{flex:1;overflow-wrap:anywhere}.dsh_messageClose{border:0;background:transparent;cursor:pointer;font:inherit;font-size:18px;line-height:18px;padding:0}@keyframes dsh-message-in{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}.dsh_message{animation:dsh-message-in .2s ease-out}'; document.head.appendChild(style); }
  const item = document.createElement('div'); item.className = 'dsh_message'; item.setAttribute('role', 'alert');
  const content = document.createElement('span'); content.className = 'dsh_messageText'; content.textContent = String(text);
  const close = document.createElement('button'); close.className = 'dsh_messageClose'; close.type = 'button'; close.setAttribute('aria-label', '关闭提示'); close.textContent = '×';
  const dismiss = () => item.remove(); close.addEventListener('click', dismiss); item.append(content, close); root.appendChild(item); window.setTimeout(dismiss, 4500);
}
module.exports = { showMessage };

},
"./section.js": function (require, module, exports) {
// dsh-desktop-session-manager — settings section UI.
//
// Renders as a native settings page (registered on `settings.section`, the
// same seat the Models/General sections use): title + intro, then two row-card
// groups — 已归档 (restore / delete) and 全部会话 (open / delete) — plus the
// delete confirmation over primitives/Modal. Visual language mirrors
// ui-settings-models' ModelsSection (section geometry, row cards, tags, pill
// buttons). A `manager` prop override keeps the render tree fixture-testable;
// in production the hook owns the list state.
const { createElement: el, Fragment, useEffect, useState, useSyncExternalStore } = require('react');
const primitives = require('@deepseek-ai/dsh-client-ui-primitives');
const { useSessionManager } = require('./use-session-manager.js');
const { ensureStyles } = require('./styles.js');
const { showMessage } = require('./message.js');

const MAX_ALL_ROWS = 50;
const noopSub = () => () => {};

function fmtDate(ms) {
  if (ms === null || ms === undefined) return null;
  const d = new Date(ms);
  if (Number.isNaN(d.getTime())) return null;
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

function fmtTokens(n) {
  if (n === null || n === undefined) return null;
  if (n >= 1e9) return `${(n / 1e9).toFixed(1)}B`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(1)}M`;
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}k`;
  return String(n);
}

/** One session row card: identity + meta line + contextual actions. */
function SessionRow({ row, current, busy, onOpen, onDelete, onRestore, t }) {
  const archived = row.archived === true;
  const title = row.title || t('row.meta.untitled');
  const metaBits = [];
  const date = fmtDate(row.createdAt);
  metaBits.push(date ?? t('row.meta.noDate'));
  if (row.tokens !== null && row.tokens !== undefined) metaBits.push(t('row.meta.tokens', { tokens: fmtTokens(row.tokens.total ?? row.tokens) }));
  if (typeof row.turns === 'number') metaBits.push(t('row.meta.turns', { count: row.turns }));

  return el(
    'li',
    { className: 'smx_rowCard' },
    el(
      'div',
      { className: 'smx_rowHead' },
      el(
        'div',
        { className: 'smx_rowIdentity' },
        el('button', { type: 'button', className: 'smx_rowName', title: t('row.open'), onClick: () => onOpen(row.id) }, title),
        current ? el('span', { className: 'smx_rowTag' }, t('row.current')) : null,
      ),
      el(
        'div',
        { className: 'smx_rowActions' },
        archived
          ? el('button', { type: 'button', className: 'smx_secondaryButton', disabled: busy, onClick: () => onRestore(row.id) }, t('row.restore'))
          : null,
        el(
          'button',
          {
            type: 'button',
            className: 'smx_dangerButton',
            disabled: busy || current,
            onClick: () => onDelete(row),
          },
          t('row.delete'),
        ),
      ),
    ),
    el('div', { className: 'smx_rowMeta' }, metaBits.join(' · ')),
  );
}

/** Delete confirmation over primitives/Modal with settings-style footer buttons. */
function ConfirmModal({ target, busy, onCancel, onConfirm, t }) {
  return el(
    primitives.Modal,
    {
      open: target !== null,
      onClose: onCancel,
      title: t('confirm.title'),
      closeLabel: t('confirm.cancel'),
      description: target !== null ? t('confirm.desc', { title: target.title || t('row.meta.untitled') }) : undefined,
      footer: el(
        Fragment,
        null,
        el('button', { type: 'button', className: 'smx_footerButton smx_footerCancel', onClick: onCancel, disabled: busy }, t('confirm.cancel')),
        el('button', { type: 'button', className: 'smx_footerButton smx_footerDanger', onClick: onConfirm, disabled: busy }, busy ? t('confirm.busy') : t('confirm.ok')),
      ),
    },
    null,
  );
}

/** The settings page. `manager` overrides the hook for fixture tests. */
function SessionManagerSection(props) {
  const { t, sessions, workspaces, close, manager: managerOverride } = props;
  const hookManager = useSessionManager(workspaces);
  const manager = managerOverride ?? hookManager;
  const { sessions: rows, loading, error, busyId, notice, remove, unarchive, clearNotice, archivedCount } = manager;
  const [confirmTarget, setConfirmTarget] = useState(null);

  useEffect(() => {
    ensureStyles();
  }, []);

  useEffect(() => {
    if (notice === null) return;
    const timer = window.setTimeout(() => clearNotice(), 2500);
    return () => window.clearTimeout(timer);
  }, [notice, clearNotice]);

  useEffect(() => {
    if (error !== null) showMessage(t('error.load', { error: String(error?.message ?? error) }));
  }, [error, t]);

  const snapshot = useSyncExternalStore(
    (fn) => (sessions?.list?.subscribe ?? noopSub)(fn),
    () => sessions?.list?.getSnapshot?.() ?? null,
    () => null,
  );
  const currentId = snapshot?.current ?? null;

  const openSession = (id) => {
    try {
      sessions?.open?.(id);
    } catch {
      /* the app's own state surfaces the failure */
    }
    close();
  };

  const confirmDelete = async () => {
    if (confirmTarget === null) return;
    const ok = await remove(confirmTarget.id);
    if (ok) setConfirmTarget(null);
  };

  const archivedRows = rows.filter((row) => row.archived);
  const activeRows = rows.filter((row) => !row.archived).slice(0, MAX_ALL_ROWS);
  const capped = rows.filter((row) => !row.archived).length > MAX_ALL_ROWS;

  const group = (heading, list, emptyKey) =>
    el(
      Fragment,
      null,
      el('p', { className: 'smx_groupTitle' }, heading),
      list.length === 0
        ? el('p', { className: 'smx_intro' }, t(emptyKey))
        : el(
            'ul',
            { className: 'smx_rows' },
            list.map((row) =>
              el(SessionRow, {
                key: row.id,
                row,
                current: row.id === currentId,
                busy: busyId === row.id,
                onOpen: openSession,
                onDelete: (target) => setConfirmTarget(target),
                onRestore: (id) => void unarchive(id),
                t,
              }),
            ),
          ),
    );

  return el(
    'div',
    { className: 'smx_section' },
    el('h2', { className: 'smx_title' }, t('title')),
    el('p', { className: 'smx_intro' }, t('intro', { count: rows.length, archived: archivedCount })),
    notice !== null
      ? el('p', { className: 'smx_savedNotice', role: 'status', 'aria-live': 'polite' }, notice.kind === 'deleted' ? t('status.deleted') : t('status.restored'))
      : null,
    loading
      ? el('p', { className: 'smx_intro' }, t('loading'))
      : el(
          Fragment,
          null,
          group(t('group.archived'), archivedRows, 'group.archived.none'),
          group(t('group.all'), activeRows, 'group.all.none'),
          capped ? el('p', { className: 'smx_notice' }, t('capNote', { limit: MAX_ALL_ROWS })) : null,
        ),
    el(ConfirmModal, {
      target: confirmTarget,
      busy: busyId === confirmTarget?.id,
      onCancel: () => setConfirmTarget(null),
      onConfirm: confirmDelete,
      t,
    }),
  );
}

module.exports = { SessionManagerSection, SessionRow, ConfirmModal };

},
"./index.js": function (require, module, exports) {
// dsh-desktop-session-manager — web client module entry.
//
// Registered as a native settings page (`settings.section`, the same seat the
// Models/General sections use): appears in the settings nav as 会话管理 and
// renders the section from ./section.js (two row-card groups + delete
// confirmation). Implementation lives in the modules under src/.
const { SessionManagerSection, SessionRow } = require('./section.js');
const { zh, en } = require('./locales.js');

/** Dictionary namespace owned by this plugin. */
const NS = 'sessionManager';

/** Services required from the client root context. */
const inject = ['slots', 'locale'];

/**
 * @param ctx - client root context (slots/locale services; sessions via ctx.get).
 */
function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'dsh-desktop-session-manager: dictionaries');
  const t = ctx.locale.bind(NS);
  ctx.slots.inject('settings.section', () =>
    ctx.slots.register(
      {
        name: 'settings.section',
        id: 'session-manager',
        order: 20,
        label: () => t('nav'),
        inject: () => ({
          t,
          // client runtime sessions service: current-session tracking + open()
          sessions: ctx.get?.('sessions') ?? null,
          // client runtime workspaces service: live archive set (merged onto
          // the server rows so archived sessions never read as missing)
          workspaces: ctx.get?.('workspaces') ?? null,
        }),
      },
      SessionManagerSection,
    ),
  );
}

exports.apply = apply;
exports.inject = inject;
// Pure section/row + merge helper re-exported for fixture-driven tests.
const { mergeArchivedFlags } = require('./use-session-manager.js');
exports.views = { SessionManagerSection, SessionRow, mergeArchivedFlags };

}
		};
		var __cache = {};
		var __require = (spec) => {
			if (spec.startsWith(".")) {
				var cached = __cache[spec];
				if (cached !== undefined) return cached.exports;
				var factory = __modules[spec];
				if (factory === undefined) throw new Error("dsh-desktop-session-manager" + ": unresolved module " + spec);
				var module = { exports: {} };
				__cache[spec] = module;
				factory(__require, module, module.exports);
				return module.exports;
			}
			return require(spec);
		};
		return __require("./index.js");
	}
});
