// dsh-desktop-web-search client bundle — GENERATED by scripts/lib/build-client-bundle.mjs, do not edit.
// Modular source lives in src/; this file is the deployed artifact.
window.__ModuleLoader__.load({
	id: "dsh-desktop-web-search",
	factory: (require) => {
		var __modules = {
"./styles.js": function (require, module, exports) {
const css = `
.dws_section{box-sizing:border-box;max-width:760px;color:var(--dsw-alias-label-primary);display:flex;flex-direction:column;gap:12px}
.dws_title{margin:0;color:var(--dsw-alias-label-primary);font-size:16px;font-weight:500;line-height:24px}
.dws_intro{max-width:680px;margin:0;color:var(--dsw-alias-label-tertiary);font-size:14px;line-height:22px}
.dws_orderLabel{margin:6px 0 0;color:var(--dsw-alias-label-caption);font-size:12px;font-weight:500;line-height:18px}
.dws_sources{overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-base)}
.dws_source{position:relative;border-bottom:1px solid var(--dsw-alias-border-l2)}
.dws_source:last-child{border-bottom:0}
.dws_sourceHeader{box-sizing:border-box;min-height:76px;display:flex;align-items:flex-start;gap:12px;padding:14px 16px}
.dws_index{box-sizing:border-box;flex:none;width:24px;height:24px;border-radius:8px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary);display:grid;place-items:center;font-size:12px;font-variant-numeric:tabular-nums;line-height:1}
.dws_sourceEnabled .dws_index{background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground)}
.dws_sourceCopy{min-width:0;flex:1}
.dws_sourceTitle{margin:0;color:var(--dsw-alias-label-primary);font-size:14px;font-weight:500;line-height:22px}
.dws_sourceDescription{max-width:610px;margin:2px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}
.dws_sourceBody{display:flex;flex-direction:column;gap:12px;padding:0 16px 16px 52px}
.dws_grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px}
.dws_field,.dws_timeout{display:flex;flex-direction:column;gap:6px}
.dws_label{display:flex;align-items:center;gap:8px;color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500;line-height:18px}
.dws_input{box-sizing:border-box;width:100%;height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);padding:0 12px;font:inherit;font-size:14px;line-height:22px;outline:none}
.dws_input:focus-visible{border-color:var(--dsw-alias-border-l4);box-shadow:0 0 0 2px var(--dsw-alias-interactive-bg-hover)}
.dws_input:disabled{cursor:default;opacity:.5}
.dws_hint{margin:0;color:var(--dsw-alias-label-caption);font-size:12px;line-height:18px}
.dws_keyState{border-radius:6px;padding:1px 6px;font-size:11px;font-weight:500;line-height:16px}
.dws_keySet{background:var(--dsw-alias-state-success-secondary);color:var(--dsw-alias-state-success-primary)}
.dws_keyMissing{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-caption)}
.dws_inlineActions{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}
.dws_switch{position:relative;flex:none;width:36px;height:22px;margin-top:1px;cursor:pointer}
.dws_switch input{position:absolute;width:1px;height:1px;opacity:0}
.dws_switchTrack{position:absolute;inset:0;border-radius:11px;background:var(--dsw-alias-border-l3);transition:background-color .16s ease}
.dws_switchTrack:after{content:"";position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:var(--dsw-alias-bg-base);box-shadow:0 1px 3px rgba(0,0,0,.18);transition:transform .16s cubic-bezier(.2,.8,.2,1)}
.dws_switch input:checked+.dws_switchTrack{background:var(--dsw-alias-button-primary-fill)}
.dws_switch input:checked+.dws_switchTrack:after{transform:translateX(14px)}
.dws_switch input:focus-visible+.dws_switchTrack{box-shadow:0 0 0 2px var(--dsw-alias-interactive-bg-hover),0 0 0 3px var(--dsw-alias-border-l4)}
.dws_switch input:disabled+.dws_switchTrack{opacity:.45}
.dws_timeout{width:180px}
.dws_timeoutSelect{width:180px}
.dws_actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;min-height:36px}
.dws_status,.dws_notice{margin-right:auto;font-size:12px;line-height:18px}
.dws_statusOk{color:var(--dsw-alias-state-success-primary)}
.dws_statusErr{color:var(--dsw-alias-state-error-primary)}
.dws_notice{color:var(--dsw-alias-state-warn-label)}
.dws_primary,.dws_secondary,.dws_textButton{box-sizing:border-box;height:36px;border-radius:18px;padding:0 14px;font:inherit;font-size:14px;line-height:22px;cursor:pointer;transition:background-color .16s ease,transform .08s ease}
.dws_primary{border:0;background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground)}
.dws_primary:hover:not(:disabled){background:var(--dsw-alias-button-primary-hover)}
.dws_secondary{border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-primary)}
.dws_secondary:hover:not(:disabled),.dws_textButton:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}
.dws_textButton{height:28px;flex:none;border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:0 8px;font-size:12px}
.dws_primary:active:not(:disabled),.dws_secondary:active:not(:disabled),.dws_textButton:active:not(:disabled){transform:scale(.98)}
.dws_primary:disabled,.dws_secondary:disabled,.dws_textButton:disabled{cursor:default;opacity:.4}
.dws_skeleton{display:flex;flex-direction:column;gap:10px;padding:14px 0}
.dws_skeleton span{height:76px;border-radius:12px;background:var(--dsw-alias-interactive-bg-hover);animation:dws-pulse 1.4s ease-in-out infinite alternate}
.dws_skeleton span:nth-child(2){animation-delay:.12s}.dws_skeleton span:nth-child(3){animation-delay:.24s}
.dws_messageRoot{position:fixed;z-index:10000;top:20px;left:50%;width:min(420px,calc(100vw - 32px));pointer-events:none;transform:translateX(-50%);display:flex;flex-direction:column;gap:8px}
.dws_message{box-sizing:border-box;padding:10px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);box-shadow:0 8px 24px rgba(0,0,0,.14);font-size:13px;line-height:20px}
@keyframes dws-pulse{from{opacity:.5}to{opacity:1}}
@media (width<=640px){.dws_grid{grid-template-columns:minmax(0,1fr)}.dws_sourceHeader{padding:12px}.dws_sourceBody{padding:0 12px 14px 48px}.dws_actions{flex-wrap:wrap}.dws_status,.dws_notice{width:100%;margin-right:0}.dws_secondary,.dws_primary{flex:1;justify-content:center}.dws_timeout,.dws_timeoutSelect{width:100%}}
@media (prefers-reduced-motion:reduce){.dws_switchTrack,.dws_switchTrack:after,.dws_primary,.dws_secondary,.dws_textButton{transition:none}.dws_skeleton span{animation:none}}
`

const style = document.createElement('style')
style.dataset.plugin = 'dsh-desktop-web-search'
style.dataset.pluginCss = 'dsh-desktop-web-search/settings'
style.textContent = css
document.head.appendChild(style)

},
"./message.js": function (require, module, exports) {
const ROOT_ID = 'dws_messageRoot'

function showMessage(text) {
  if (typeof document === 'undefined' || !text) return
  let root = document.getElementById(ROOT_ID)
  if (!root) {
    root = document.createElement('div')
    root.id = ROOT_ID
    root.className = 'dws_messageRoot'
    root.setAttribute('aria-live', 'polite')
    document.body.appendChild(root)
  }
  const item = document.createElement('div')
  item.className = 'dws_message'
  item.setAttribute('role', 'status')
  item.textContent = String(text)
  root.appendChild(item)
  window.setTimeout(() => item.remove(), 4200)
}

module.exports = { showMessage }

},
"./locales.js": function (require, module, exports) {
const NS = 'desktop-web-search'

const zh = {
  nav: '联网搜索',
  title: '联网搜索',
  intro: '按顺序尝试搜索来源。上游不可用或不支持原生搜索时，会自动进入下一层。',
  customTitle: '第三方搜索',
  customDescription: '使用独立搜索 API，优先于模型原生搜索。',
  provider: '搜索协议',
  providerNone: '不使用第三方搜索',
  providerExa: 'Exa',
  providerTavily: 'Tavily',
  providerBrave: 'Brave Search',
  providerPerplexity: 'Perplexity Search',
  providerGeneric: '通用 JSON Search API',
  baseURL: 'Base URL',
  baseURLHint: '留空使用所选服务的官方地址；通用协议必须填写。',
  apiKeyEnv: '凭据名称',
  apiKeyEnvHint: '只保存凭据引用，API Key 写入 DSH 本机凭据库。',
  apiKey: 'API Key',
  apiKeySet: '已配置',
  apiKeyMissing: '未配置',
  apiKeyPlaceholder: '留空保持现有密钥',
  clearKey: '清除密钥',
  nativeTitle: '当前模型原生搜索',
  nativeDescription: '跟随当前会话模型。支持 OpenAI Responses 与 Anthropic Messages 原生搜索；不支持时自动跳过。',
  deepseekTitle: 'DeepSeek 官方兜底',
  deepseekDescription: '复用“模型”中的 DeepSeek 凭据，仅在前两层失败后调用。',
  timeout: '单层超时',
  seconds: '{seconds} 秒',
  save: '保存',
  saving: '保存中…',
  saved: '搜索设置已保存',
  test: '测试第三方搜索',
  testing: '测试中…',
  testOk: '连接成功，返回 {count} 条结果',
  readOnly: '当前设置只读。',
  loadFailed: '读取搜索设置失败',
  conflict: '设置已在其他位置修改，请重试。',
  unavailable: '远程浏览器不能修改本机搜索设置。',
  sourceOrder: '搜索顺序',
  enabled: '启用',
}

const en = {
  nav: 'Web search',
  title: 'Web search',
  intro: 'Search sources are tried in order. An unavailable or unsupported source automatically falls through.',
  customTitle: 'Third-party search',
  customDescription: 'Use a dedicated search API before model-native search.',
  provider: 'Search protocol',
  providerNone: 'No third-party search',
  providerExa: 'Exa',
  providerTavily: 'Tavily',
  providerBrave: 'Brave Search',
  providerPerplexity: 'Perplexity Search',
  providerGeneric: 'Generic JSON Search API',
  baseURL: 'Base URL',
  baseURLHint: 'Leave blank for the selected service default. Generic requires a URL.',
  apiKeyEnv: 'Credential name',
  apiKeyEnvHint: 'Only the reference is stored here. The API key goes to the local DSH credential store.',
  apiKey: 'API key',
  apiKeySet: 'Configured',
  apiKeyMissing: 'Not configured',
  apiKeyPlaceholder: 'Leave blank to keep the stored key',
  clearKey: 'Clear key',
  nativeTitle: 'Current model native search',
  nativeDescription: 'Follows the session model. OpenAI Responses and Anthropic Messages native search are supported; other protocols are skipped.',
  deepseekTitle: 'DeepSeek fallback',
  deepseekDescription: 'Reuses the DeepSeek credential from Models and runs only after the first two sources fail.',
  timeout: 'Per-source timeout',
  seconds: '{seconds} seconds',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Search settings saved',
  test: 'Test third-party search',
  testing: 'Testing…',
  testOk: 'Connection succeeded with {count} results',
  readOnly: 'Settings are read-only.',
  loadFailed: 'Failed to load search settings',
  conflict: 'Settings changed elsewhere. Please retry.',
  unavailable: 'Remote browsers cannot change local search settings.',
  sourceOrder: 'Search order',
  enabled: 'Enabled',
}

module.exports = { NS, zh, en }

},
"./section.js": function (require, module, exports) {
const react = require('react')
const { jsx, jsxs } = require('react/jsx-runtime')
const { showMessage } = require('./message.js')

const ENDPOINT = '/desktop-web-search'
const PROVIDER_ENDPOINTS = {
  exa: 'https://api.exa.ai/search',
  tavily: 'https://api.tavily.com/search',
  brave: 'https://api.search.brave.com/res/v1/web/search',
  perplexity: 'https://api.perplexity.ai/search',
  generic: 'https://search.example.com/search',
}

async function request(path, init) {
  const response = await fetch(`${ENDPOINT}${path}`, init)
  const payload = await response.json().catch(() => ({}))
  if (!response.ok || payload?.ok !== true) {
    const error = new Error(payload?.error?.message ?? `HTTP ${String(response.status)}`)
    error.code = payload?.error?.code
    throw error
  }
  return payload.value
}

function draftFromValue(value) {
  return {
    customProvider: value?.customProvider ?? 'none',
    customBaseURL: value?.customBaseURL ?? '',
    customApiKeyEnv: value?.customApiKeyEnv ?? 'DSH_WEB_SEARCH_API_KEY',
    nativeEnabled: value?.nativeEnabled !== false,
    deepseekFallback: value?.deepseekFallback !== false,
    sourceTimeoutMs: Number(value?.sourceTimeoutMs ?? 15000),
    apiKey: '',
  }
}

function Toggle({ checked, disabled, label, onChange }) {
  return jsxs('label', { className: 'dws_switch', children: [
    jsx('input', { type: 'checkbox', checked, disabled, onChange: (event) => onChange(event.target.checked), 'aria-label': label }),
    jsx('span', { className: 'dws_switchTrack', 'aria-hidden': 'true' }),
  ] })
}

function SourceHeader({ index, title, description, enabled, disabled, onToggle, fixed }) {
  return jsxs('div', { className: 'dws_sourceHeader', children: [
    jsx('span', { className: 'dws_index', 'aria-hidden': 'true', children: String(index) }),
    jsxs('div', { className: 'dws_sourceCopy', children: [
      jsx('h3', { className: 'dws_sourceTitle', children: title }),
      jsx('p', { className: 'dws_sourceDescription', children: description }),
    ] }),
    fixed ? null : jsx(Toggle, { checked: enabled, disabled, label: title, onChange: onToggle }),
  ] })
}

function WebSearchSection({ t, isLoopback, subscribe }) {
  const [view, setView] = react.useState(null)
  const [writable, setWritable] = react.useState(true)
  const [credential, setCredential] = react.useState({ configured: false, writable: false })
  const [draft, setDraft] = react.useState(null)
  const [busy, setBusy] = react.useState(false)
  const [testing, setTesting] = react.useState(false)
  const [error, setError] = react.useState(null)
  const [notice, setNotice] = react.useState(null)

  const read = react.useCallback(async () => {
    try {
      const value = await request('/settings')
      setView(value.view)
      setWritable(value.writable !== false)
      setCredential(value.credential ?? { configured: false, writable: false })
      setDraft((current) => current ?? draftFromValue(value.view?.value))
      setError(null)
    } catch (cause) {
      setError(String(cause?.message ?? cause))
    }
  }, [])

  react.useEffect(() => {
    read()
    return subscribe(read)
  }, [read, subscribe])

  react.useEffect(() => {
    if (error) showMessage(`${t('loadFailed')}（${error}）`)
  }, [error, t])

  if (!isLoopback) {
    return jsxs('section', { className: 'dws_section', 'aria-label': t('title'), children: [
      jsx('h2', { className: 'dws_title', children: t('title') }),
      jsx('p', { className: 'dws_intro', children: t('unavailable') }),
    ] })
  }
  if (view === null || draft === null) {
    return jsxs('section', { className: 'dws_section', 'aria-label': t('title'), children: [
      jsx('h2', { className: 'dws_title', children: t('title') }),
      jsx('div', { className: 'dws_skeleton', 'aria-label': t('loadFailed'), children: [0, 1, 2].map((key) => jsx('span', {}, key)) }),
    ] })
  }

  const disabled = busy || testing || !writable
  const customEnabled = draft.customProvider !== 'none'
  const update = (patch) => {
    setNotice(null)
    setDraft((current) => ({ ...current, ...patch }))
  }

  const saveCredential = async () => {
    const key = draft.apiKey.trim()
    if (!key) return credential
    return request('/credential', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ ref: draft.customApiKeyEnv.trim() || 'DSH_WEB_SEARCH_API_KEY', value: key }),
    })
  }

  const save = async () => {
    setBusy(true)
    setNotice(null)
    try {
      const fields = ['customProvider', 'customBaseURL', 'customApiKeyEnv', 'nativeEnabled', 'deepseekFallback', 'sourceTimeoutMs']
      const ops = fields.map((field) => ({ op: 'set', path: [field], value: typeof draft[field] === 'string' ? draft[field].trim() : draft[field] }))
      const value = await request('/settings', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ops, expectedRevision: view.revision }),
      })
      const nextCredential = await saveCredential()
      setView(value.view)
      setWritable(value.writable !== false)
      setCredential(nextCredential ?? value.credential)
      setDraft({ ...draftFromValue(value.view?.value), apiKey: '' })
      setNotice({ kind: 'ok', text: t('saved') })
    } catch (cause) {
      const text = cause?.code === 'settings-conflict' ? t('conflict') : String(cause?.message ?? cause)
      setNotice({ kind: 'err', text })
      showMessage(text)
      if (cause?.code === 'settings-conflict') await read()
    } finally {
      setBusy(false)
    }
  }

  const clearKey = async () => {
    setBusy(true)
    try {
      const next = await request('/credential', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ref: draft.customApiKeyEnv.trim() || 'DSH_WEB_SEARCH_API_KEY', clear: true }),
      })
      setCredential(next)
      setDraft((current) => ({ ...current, apiKey: '' }))
    } catch (cause) {
      showMessage(String(cause?.message ?? cause))
    } finally {
      setBusy(false)
    }
  }

  const test = async () => {
    setTesting(true)
    setNotice(null)
    try {
      const value = await request('/test', { method: 'POST' })
      setNotice({ kind: 'ok', text: t('testOk', { count: value.count }) })
    } catch (cause) {
      const text = String(cause?.message ?? cause)
      setNotice({ kind: 'err', text })
      showMessage(text)
    } finally {
      setTesting(false)
    }
  }

  return jsxs('section', { className: 'dws_section', 'aria-label': t('title'), children: [
    jsx('h2', { className: 'dws_title', children: t('title') }),
    jsx('p', { className: 'dws_intro', children: t('intro') }),
    jsx('p', { className: 'dws_orderLabel', children: t('sourceOrder') }),
    jsxs('div', { className: 'dws_sources', children: [
      jsxs('div', { className: `dws_source${customEnabled ? ' dws_sourceEnabled' : ''}`, children: [
        jsx(SourceHeader, {
          index: 1,
          title: t('customTitle'),
          description: t('customDescription'),
          enabled: customEnabled,
          disabled,
          onToggle: (checked) => update({ customProvider: checked ? 'exa' : 'none' }),
        }),
        customEnabled ? jsxs('div', { className: 'dws_sourceBody', children: [
          jsxs('label', { className: 'dws_field', children: [
            jsx('span', { className: 'dws_label', children: t('provider') }),
            jsx('select', { className: 'dws_input', value: draft.customProvider, disabled, onChange: (event) => update({ customProvider: event.target.value, customBaseURL: '' }), children: [
              jsx('option', { value: 'exa', children: t('providerExa') }),
              jsx('option', { value: 'tavily', children: t('providerTavily') }),
              jsx('option', { value: 'brave', children: t('providerBrave') }),
              jsx('option', { value: 'perplexity', children: t('providerPerplexity') }),
              jsx('option', { value: 'generic', children: t('providerGeneric') }),
            ] }),
          ] }),
          jsxs('label', { className: 'dws_field', children: [
            jsx('span', { className: 'dws_label', children: t('baseURL') }),
            jsx('input', { className: 'dws_input', type: 'url', value: draft.customBaseURL, placeholder: PROVIDER_ENDPOINTS[draft.customProvider] ?? '', disabled, spellCheck: false, onChange: (event) => update({ customBaseURL: event.target.value }) }),
            jsx('span', { className: 'dws_hint', children: t('baseURLHint') }),
          ] }),
          jsxs('div', { className: 'dws_grid', children: [
            jsxs('label', { className: 'dws_field', children: [
              jsx('span', { className: 'dws_label', children: t('apiKeyEnv') }),
              jsx('input', { className: 'dws_input', value: draft.customApiKeyEnv, disabled, spellCheck: false, onChange: (event) => update({ customApiKeyEnv: event.target.value }) }),
            ] }),
            jsxs('label', { className: 'dws_field', children: [
              jsxs('span', { className: 'dws_label', children: [
                t('apiKey'),
                jsx('span', { className: credential.configured ? 'dws_keyState dws_keySet' : 'dws_keyState dws_keyMissing', children: credential.configured ? t('apiKeySet') : t('apiKeyMissing') }),
              ] }),
              jsx('input', { className: 'dws_input', type: 'password', value: draft.apiKey, placeholder: t('apiKeyPlaceholder'), disabled, autoComplete: 'off', spellCheck: false, onChange: (event) => update({ apiKey: event.target.value }) }),
            ] }),
          ] }),
          jsxs('div', { className: 'dws_inlineActions', children: [
            jsx('span', { className: 'dws_hint', children: t('apiKeyEnvHint') }),
            credential.configured ? jsx('button', { type: 'button', className: 'dws_textButton', disabled, onClick: clearKey, children: t('clearKey') }) : null,
          ] }),
        ] }) : null,
      ] }),
      jsxs('div', { className: `dws_source${draft.nativeEnabled ? ' dws_sourceEnabled' : ''}`, children: [
        jsx(SourceHeader, { index: 2, title: t('nativeTitle'), description: t('nativeDescription'), enabled: draft.nativeEnabled, disabled, onToggle: (checked) => update({ nativeEnabled: checked }) }),
      ] }),
      jsxs('div', { className: `dws_source${draft.deepseekFallback ? ' dws_sourceEnabled' : ''}`, children: [
        jsx(SourceHeader, { index: 3, title: t('deepseekTitle'), description: t('deepseekDescription'), enabled: draft.deepseekFallback, disabled, onToggle: (checked) => update({ deepseekFallback: checked }) }),
      ] }),
    ] }),
    jsxs('label', { className: 'dws_timeout', children: [
      jsx('span', { className: 'dws_label', children: t('timeout') }),
      jsx('select', { className: 'dws_input dws_timeoutSelect', value: String(draft.sourceTimeoutMs), disabled, onChange: (event) => update({ sourceTimeoutMs: Number(event.target.value) }), children: [10000, 15000, 20000, 30000].map((ms) => jsx('option', { value: String(ms), children: t('seconds', { seconds: ms / 1000 }) }, ms)) }),
    ] }),
    jsxs('div', { className: 'dws_actions', children: [
      !writable ? jsx('span', { className: 'dws_notice', children: t('readOnly') }) : null,
      notice ? jsx('span', { className: notice.kind === 'ok' ? 'dws_status dws_statusOk' : 'dws_status dws_statusErr', role: notice.kind === 'err' ? 'alert' : 'status', children: notice.text }) : null,
      jsx('button', { type: 'button', className: 'dws_secondary', disabled: disabled || !customEnabled, onClick: test, children: testing ? t('testing') : t('test') }),
      jsx('button', { type: 'button', className: 'dws_primary', disabled, onClick: save, children: busy ? t('saving') : t('save') }),
    ] }),
  ] })
}

module.exports = { WebSearchSection, draftFromValue }

},
"./index.js": function (require, module, exports) {
require('./styles.js')
const { WebSearchSection } = require('./section.js')
const { NS, zh, en } = require('./locales.js')

const inject = ['slots', 'locale', 'connection', 'remote']

function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'dsh-desktop-web-search: dictionaries')
  const t = ctx.locale.bind(NS)
  const connection = ctx.get('connection')
  const remote = ctx.get('remote')
  ctx.slots.inject('settings.section', () => ctx.slots.register({
    name: 'settings.section',
    id: 'web-search',
    order: 4,
    label: () => t('nav'),
    locale: NS,
    inject: () => ({
      t,
      isLoopback: connection.isLoopback,
      subscribe: (handler) => {
        const offDocument = remote.$on('settings/document-updated', handler)
        const offReset = ctx.on('connection/reset', handler)
        return () => { offDocument(); offReset() }
      },
    }),
  }, WebSearchSection))
}

exports.apply = apply
exports.inject = inject
exports.views = { WebSearchSection }

}
		};
		var __cache = {};
		var __require = (spec) => {
			if (spec.startsWith(".")) {
				var cached = __cache[spec];
				if (cached !== undefined) return cached.exports;
				var factory = __modules[spec];
				if (factory === undefined) throw new Error("dsh-desktop-web-search" + ": unresolved module " + spec);
				var module = { exports: {} };
				__cache[spec] = module;
				factory(__require, module, module.exports);
				return module.exports;
			}
			return require(spec);
		};
		return __require("./index.js");
	}
});
