// dsh-desktop-bridge client bundle — GENERATED by scripts/lib/build-client-bundle.mjs, do not edit.
// Modular source lives in src/; this file is the deployed artifact.
window.__ModuleLoader__.load({
	id: "dsh-desktop-bridge",
	factory: (require) => {
		var __modules = {
"./styles.js": function (require, module, exports) {
// dsh-desktop-bridge — panel stylesheet (injected once per document).
// Side effect module: index.js requires it first so the styles install when
// the bundle loads, matching the pre-split bundle's load-time behavior.
const css = `
.dbb_trigger{box-sizing:border-box;cursor:pointer;width:calc(100% + 8px);height:44px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:12px;flex:none;align-items:center;gap:8px;margin:4px -4px 8px;padding:0 10px;font-family:inherit;font-size:14px;line-height:22px;display:flex;overflow:hidden}
.dbb_trigger:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dbb_trigger.dbb_rail{background:0 0;border:none;border-radius:50%;justify-content:center;gap:0;width:36px;height:36px;margin:8px 0 10px;padding:0}
.dbb_avatar{width:24px;height:24px;border-radius:50%;background:color-mix(in srgb, var(--dsw-alias-state-business-primary) 12%, transparent);color:var(--dsw-alias-state-business-primary);flex:none;justify-content:center;align-items:center;display:flex}
.dbb_icon{color:var(--dsw-alias-state-business-primary);flex:none;display:inline-flex}
.dbb_label{white-space:nowrap;overflow:hidden}
.dbb_amount{color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums;flex:none;margin-left:auto;font-size:12px;line-height:16px}
.dbb_amount.dbb_low{color:var(--dsw-alias-state-warn-label)}
.dbb_amount.dbb_off{color:var(--dsw-alias-label-caption)}
.dbb_amount.dbb_err{color:var(--dsw-alias-state-error-primary)}

.dbb_panel{z-index:40;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-base);width:404px;max-width:calc(100vw - 24px);max-height:min(74vh, 680px);box-shadow:var(--dsw-shadow-lv2);--dsh-scrollbar-thumb:var(--dsw-alias-scrollbar-bg-l2);--dsh-scrollbar-thumb-hover:var(--dsw-alias-scrollbar-hover-l2);border-radius:12px;flex-direction:column;display:flex;position:fixed;bottom:136px;left:12px;overflow:hidden}
.dbb_header{box-sizing:border-box;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);flex:none;justify-content:space-between;align-items:center;min-height:44px;padding:10px 12px;display:flex}
.dbb_titleWrap{flex-direction:column;gap:1px;min-width:0;display:flex}
.dbb_title{align-items:center;gap:8px;color:var(--dsw-alias-label-primary);font-size:13px;font-weight:500;line-height:20px;display:flex}
.dbb_title .dbb_icon{color:var(--dsw-alias-state-business-primary)}
.dbb_subtitle{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dbb_actions{align-items:center;gap:2px;display:flex}
.dbb_iconBtn{width:26px;height:26px;color:var(--dsw-alias-label-tertiary);cursor:pointer;background:0 0;border:none;border-radius:999px;justify-content:center;align-items:center;padding:0;display:inline-flex}
.dbb_iconBtn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}
.dbb_iconBtn:disabled{opacity:.45;cursor:default}
.dbb_spin{animation:dbb_spin .9s linear infinite}
@keyframes dbb_spin{to{transform:rotate(360deg)}}
.dbb_body{flex:1;min-height:0;padding:4px 12px 12px;overflow-y:auto}
.dbb_card{background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:10px;margin-top:8px;padding:10px 12px}
.dbb_providerHead{justify-content:space-between;align-items:center;gap:8px;margin-bottom:6px;display:flex}
.dbb_providerName{color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500;line-height:18px}
.dbb_secTitle{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;text-transform:uppercase;letter-spacing:.4px;margin:14px 2px 6px}
.dbb_balanceTop{align-items:baseline;gap:6px;display:flex}
.dbb_balanceBig{color:var(--dsw-alias-label-primary);font-size:26px;font-weight:600;font-variant-numeric:tabular-nums;line-height:32px}
.dbb_currency{color:var(--dsw-alias-label-caption);font-size:13px;font-variant-numeric:tabular-nums}
.dbb_balanceSub{flex-wrap:wrap;gap:4px 14px;margin-top:6px;display:flex}
.dbb_kv{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}
.dbb_kv b{color:var(--dsw-alias-label-secondary);font-weight:500;font-variant-numeric:tabular-nums}
.dbb_badge{display:inline-flex;align-items:center;border-radius:999px;padding:1px 8px;font-size:11px;line-height:16px}
.dbb_badgeOk{background:color-mix(in srgb, var(--dsw-alias-state-success-primary) 14%, transparent);color:var(--dsw-alias-state-success-primary)}
.dbb_badgeWarn{background:color-mix(in srgb, var(--dsw-alias-state-warn-primary) 14%, transparent);color:var(--dsw-alias-state-warn-label)}
.dbb_badgeErr{background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 14%, transparent);color:var(--dsw-alias-state-error-primary)}
.dbb_grid{grid-template-columns:1fr 1fr;gap:8px;display:grid}
.dbb_stat{background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:10px;flex-direction:column;gap:2px;padding:8px 10px;display:flex}
.dbb_statLabel{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px}
.dbb_statValue{color:var(--dsw-alias-label-primary);font-size:15px;font-weight:500;font-variant-numeric:tabular-nums;line-height:20px}
.dbb_row{justify-content:space-between;gap:8px;font-size:12px;line-height:18px;display:flex}
.dbb_row+.dbb_row{margin-top:4px}
.dbb_rowLabel{color:var(--dsw-alias-label-secondary);min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dbb_rowValue{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums;flex:none}
.dbb_modelRow{flex-direction:column;gap:4px;display:flex}
.dbb_modelRow+.dbb_modelRow{margin-top:8px}
.dbb_barTrack{background:var(--dsw-alias-interactive-bg-hover-solid);border-radius:999px;height:4px;overflow:hidden}
.dbb_barFill{background:var(--dsw-alias-state-business-primary);border-radius:999px;height:100%;transition:width .3s var(--ds-ease-in-out, ease)}
.dbb_chart{width:100%;height:auto;margin-top:4px;display:block}
.dbb_chart rect.dbb_bar{fill:var(--dsw-alias-state-business-primary);opacity:.85}
.dbb_chart rect.dbb_bar:hover{opacity:1}
.dbb_session{flex-direction:column;gap:2px;border-bottom:1px solid var(--dsw-alias-border-l2);padding:7px 0;display:flex}
.dbb_session:last-child{border-bottom:none}
.dbb_sessionTop{justify-content:space-between;align-items:baseline;gap:8px;display:flex}
.dbb_sessionTitle{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dbb_sessionTokens{color:var(--dsw-alias-label-primary);font-size:12px;font-variant-numeric:tabular-nums;flex:none}
.dbb_sessionMeta{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dbb_empty{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;text-align:center;padding:22px 8px}
.dbb_note{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;margin-top:8px}
.dbb_error{color:var(--dsw-alias-state-error-primary);font-size:12px;line-height:18px}

.dbb_about{max-width:640px;color:var(--dsw-alias-label-primary);flex-direction:column;gap:10px;display:flex}
.dbb_aboutTitle{color:var(--dsw-alias-label-primary);margin:0;font-size:16px;font-weight:500;line-height:24px}
.dbb_aboutIntro{color:var(--dsw-alias-label-tertiary);margin:0;font-size:14px;line-height:22px}
.dbb_aboutCard{background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:12px;flex-direction:column;gap:6px;padding:14px 16px;display:flex}
.dbb_aboutHead{align-items:center;gap:12px;margin-bottom:4px;display:flex}
.dbb_aboutLogo{background:color-mix(in srgb, var(--dsw-alias-state-business-primary) 12%, transparent);color:var(--dsw-alias-state-business-primary);border-radius:10px;justify-content:center;align-items:center;width:40px;height:40px;flex:none;display:flex}
.dbb_aboutTitleWrap{flex-direction:column;min-width:0;display:flex}
.dbb_aboutName{font-size:14px;font-weight:600;line-height:20px}
.dbb_aboutVer{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;font-variant-numeric:tabular-nums}
.dbb_aboutRows{flex-direction:column;display:flex}
.dbb_aboutLink{color:var(--dsw-alias-state-business-primary);font:inherit;cursor:pointer;background:0 0;border:none;padding:0;font-size:12px;line-height:18px}
.dbb_aboutLink:hover{text-decoration:underline}
.dbb_aboutActions{flex-wrap:wrap;gap:8px;margin-top:6px;display:flex}
.dbb_aboutPrimary{box-sizing:border-box;height:32px;font:inherit;cursor:pointer;background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground);border:none;border-radius:8px;align-items:center;gap:4px;padding:0 14px;font-size:13px;line-height:20px;display:inline-flex}
.dbb_aboutPrimary:hover:not(:disabled){filter:brightness(1.06)}
.dbb_aboutPrimary:disabled{opacity:.5;cursor:default}
.dbb_aboutSecondary{box-sizing:border-box;height:32px;font:inherit;cursor:pointer;background:0 0;color:var(--dsw-alias-label-primary);border:1px solid var(--dsw-alias-border-l2);border-radius:8px;align-items:center;gap:4px;padding:0 14px;font-size:13px;line-height:20px;display:inline-flex}
.dbb_aboutSecondary:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dbb_aboutRelease{align-self:flex-start;text-align:left}
.dbb_aboutStatus{color:var(--dsw-alias-state-success-primary);margin:0;font-size:12px;line-height:18px}
`;

const TAG_ID = 'desktop-balance.css';

/** Install the stylesheet exactly once per document. */
function ensureStyles() {
  if (typeof document === 'undefined') return;
  if (document.querySelector('style[data-plugin-css=' + JSON.stringify(TAG_ID) + ']') === null) {
    const tag = document.createElement('style');
    tag.dataset.plugin = 'dsh-desktop-bridge';
    tag.dataset.pluginCss = TAG_ID;
    tag.textContent = css;
    document.head.appendChild(tag);
  }
}

// install on bundle load (the pre-split bundle did this inline at load time)
ensureStyles();

module.exports = { ensureStyles };

},
"./helpers.js": function (require, module, exports) {
// dsh-desktop-bridge — formatting helpers and cost estimation.
function fmtTokens(n) {
  if (!Number.isFinite(n) || n <= 0) return "0";
  if (n >= 1e9) return (n / 1e9).toFixed(2) + "B";
  if (n >= 1e6) return (n / 1e6).toFixed(2) + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1) + "K";
  return String(Math.round(n));
}
function fmtMoney(n) {
  if (!Number.isFinite(n)) return "—";
  return "≈ $" + (n < 0.01 && n > 0 ? "<0.01" : n.toFixed(2));
}
function fmtUsd(v) {
  if (!Number.isFinite(v)) return "—";
  if (v >= 1e9) return "$" + (v / 1e9).toFixed(2) + "B";
  if (v >= 1e6) return "$" + (v / 1e6).toFixed(2) + "M";
  return "$" + v.toFixed(2);
}
function fmtDate(ms) {
  if (!Number.isFinite(ms)) return "";
  const d = new Date(ms);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")} ${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

/** Approximate cost from the DeepSeek public price list (USD / 1M tokens).
 *  Third-party models are skipped: their platforms bill independently and
 *  the panel shows the platform's own billing totals instead. */
const PRICING = {
  "deepseek-reasoner": { miss: 0.55, hit: 0.14, out: 2.19 },
  default: { miss: 0.28, hit: 0.028, out: 0.42 },
};
function estimateCost(report) {
  if (!report?.byModel?.length) return 0;
  let cost = 0;
  for (const row of report.byModel) {
    const price = PRICING[row.model] ?? null;
    if (price === null) continue; // third-party platform — not DeepSeek-priced
    cost += (row.tokens.input / 1e6) * price.miss
      + (row.tokens.cacheRead / 1e6) * price.hit
      + (row.tokens.cacheWrite / 1e6) * price.hit
      + (row.tokens.output / 1e6) * price.out;
  }
  return cost;
}

module.exports = { fmtTokens, fmtMoney, fmtUsd, fmtDate, estimateCost };

},
"./locales.js": function (require, module, exports) {
// dsh-desktop-bridge — dictionary namespace `desktop-balance`.
// Simplified Chinese is the key-set source of truth; English mirrors it.
const zh = {
  "badge": "余额",
  "badge.usage": "消费",
  "badge.unconfigured": "未配置 Key",
  "badge.offline": "余额组件不可用",
  "panel.title": "账户与用量",
  "panel.refresh": "刷新",
  "panel.close": "关闭",
  "balance.title": "账户余额",
  "balance.topped": "充值",
  "balance.granted": "赠送",
  "balance.unavailable": "账户余额不可用",
  "balance.none": "未获取",
  "balance.low": "余额不足",
  "balance.ok": "可用",
  "balance.usageNote": "该平台按量计费，无账户余额概念；数据来自平台账单接口",
  "balance.unsupported": "不支持",
  "balance.unsupportedNote": "该平台未提供可通过 API Key 查询的余额/账单接口",
  "usage.totalUsage": "累计消费",
  "usage.softLimit": "软限额",
  "usage.hardLimit": "硬限额",
  "usage.payment": "支付方式",
  "usage.paymentYes": "已绑定",
  "usage.paymentNo": "未绑定",
  "registeredAt": "Key 登记于",
  "registeredAt.none": "未登记 Key，显示全部历史",
  "usage.title": "Token 消费",
  "usage.total": "总 Token",
  "usage.input": "输入",
  "usage.cacheRead": "缓存命中",
  "usage.output": "输出",
  "usage.cost": "预估成本",
  "usage.costNote": "按 DeepSeek 官方公开价目估算（USD），仅覆盖 DeepSeek 模型；第三方平台成本以平台账单为准",
  "usage.models": "模型分布",
  "usage.days": "近 14 天",
  "usage.sessions": "最近会话",
  "usage.sessionsCount": "共 {count} 个会话 · 活跃 {days} 天",
  "usage.empty": "暂无消费数据",
  "usage.error": "读取消费数据失败",
  "turns": "{count} 轮",
  "session.unknown": "未知模型",
  "session.untitled": "(未命名会话)",
  "about.nav": "关于",
  "about.title": "关于",
  "about.intro": "DeepSeek Harness 的 Windows 桌面壳，由 Anixuil 开发维护。",
  "about.version": "壳版本 {version}",
  "about.author": "作者",
  "about.dshVersion": "dsh 内核",
  "about.blog": "博客",
  "about.repo": "GitHub 仓库",
  "about.note": "欢迎访问博客 www.anixuil.top 了解更多，或在 GitHub 仓库查看源码、提交 Issue、参与共建。",
  "about.check": "检查更新",
  "about.checking": "正在检查更新…",
  "about.repoBtn": "访问 GitHub 仓库",
  "about.release": "前往 Releases 下载新版本",
  "about.latest": "当前已是最新版本",
  "about.appUpdate": "应用有新版本 {version}",
  "about.dshUpdate": "dsh 内核有新版本 {version}",
  "about.offline": "无法连接桌面壳服务",
};
const en = {
  "badge": "Balance",
  "badge.usage": "Usage",
  "badge.unconfigured": "No key configured",
  "badge.offline": "Balance widget unavailable",
  "panel.title": "Account & Usage",
  "panel.refresh": "Refresh",
  "panel.close": "Close",
  "balance.title": "Account balance",
  "balance.topped": "Topped up",
  "balance.granted": "Granted",
  "balance.unavailable": "Balance unavailable",
  "balance.none": "Not fetched",
  "balance.low": "Low balance",
  "balance.ok": "Available",
  "balance.usageNote": "This platform bills by usage and has no account-balance concept; data comes from its billing API",
  "balance.unsupported": "Unsupported",
  "balance.unsupportedNote": "This platform exposes no key-accessible balance/billing endpoint",
  "usage.totalUsage": "Total usage",
  "usage.softLimit": "Soft limit",
  "usage.hardLimit": "Hard limit",
  "usage.payment": "Payment method",
  "usage.paymentYes": "Bound",
  "usage.paymentNo": "Not bound",
  "registeredAt": "Key registered on",
  "registeredAt.none": "No key registered — showing all history",
  "usage.title": "Token consumption",
  "usage.total": "Total tokens",
  "usage.input": "Input",
  "usage.cacheRead": "Cache hit",
  "usage.output": "Output",
  "usage.cost": "Estimated cost",
  "usage.costNote": "Estimated from the public DeepSeek price list (USD), DeepSeek models only; third-party costs come from the platform's own billing",
  "usage.models": "By model",
  "usage.days": "Last 14 days",
  "usage.sessions": "Recent sessions",
  "usage.sessionsCount": "{count} sessions · {days} active days",
  "usage.empty": "No consumption data yet",
  "usage.error": "Failed to read consumption data",
  "turns": "{count} turns",
  "session.unknown": "Unknown model",
  "session.untitled": "(untitled session)",
  "about.nav": "About",
  "about.title": "About",
  "about.intro": "The Windows desktop shell for DeepSeek Harness, built and maintained by Anixuil.",
  "about.version": "Shell version {version}",
  "about.author": "Author",
  "about.dshVersion": "dsh core",
  "about.blog": "Blog",
  "about.repo": "GitHub repository",
  "about.note": "Visit the blog at www.anixuil.top, or browse the source, file issues and contribute on GitHub.",
  "about.check": "Check for updates",
  "about.checking": "Checking for updates…",
  "about.repoBtn": "Open GitHub repository",
  "about.release": "Download from Releases",
  "about.latest": "You are up to date",
  "about.appUpdate": "App update {version} available",
  "about.dshUpdate": "dsh core update {version} available",
  "about.offline": "Desktop shell service unavailable",
};

const NS = "desktop-balance";

module.exports = { zh, en, NS };

},
"./balance-badge.js": function (require, module, exports) {
// dsh-desktop-bridge — sidebar footer badge: balance/usage trigger + panel host.
const react = require('react');
const { jsx, jsxs, Fragment } = require('react/jsx-runtime');
const primitives = require('@deepseek-ai/dsh-client-ui-primitives');
const { BalancePanel } = require('./balance-panel.js');

const noopSub = () => () => {};

/** The active platform entry for a model selection (falls back to DeepSeek). */
function activeProvider(providers, selection) {
  if (!Array.isArray(providers) || providers.length === 0) return null;
  if (selection?.provider) {
    const match = providers.find((p) => p.id === selection.provider);
    if (match) return match;
  }
  return providers.find((p) => p.id === "deepseek-official") ?? providers[0];
}

/** Card amount text for one provider entry, or null when unavailable. */
function providerAmount(provider) {
  if (!provider || !provider.configured) return null;
  if (provider.kind === "balance") {
    const info = provider.balance?.balance_infos?.[0];
    if (info && provider.balance?.is_available !== false) {
      return `${info.total_balance} ${info.currency ?? ""}`.trim();
    }
    return null;
  }
  if (provider.kind === "usage") {
    const u = provider.usage?.total_usage_usd;
    if (Number.isFinite(u)) return `$${u.toFixed(2)}`;
    return null;
  }
  return null;
}

function BalanceBadge(props) {
  const { wide, t, sessions, modelDirectories } = props;
  const [balance, setBalance] = react.useState(null);
  const [error, setError] = react.useState(false);
  const [open, setOpen] = react.useState(false);

  const loadBalance = react.useCallback(async (signal) => {
    try {
      const resp = await fetch("/desktop/balance", { signal });
      if (!resp.ok) throw new Error("http " + resp.status);
      const data = await resp.json();
      if (data?.ok !== true) throw new Error(data?.error ?? "shell error");
      setBalance(data);
      setError(false);
      return data;
    } catch (e) {
      if (e?.name === "AbortError") return null;
      setError(true);
      return null;
    }
  }, []);

  // Dynamic cadence: 5s while a turn is running or right after it ends,
  // 5s during startup / while no platform has healthy data yet, and the
  // normal 60s idle cadence otherwise. This makes the card populate as
  // soon as the shell is ready instead of waiting a full minute.
  react.useEffect(() => {
    let alive = true;
    let timer = null;
    let prevRunning = false;
    const schedule = (delay) => {
      window.clearTimeout(timer);
      timer = window.setTimeout(tick, delay);
    };
    const tick = async () => {
      if (!alive) return;
      let running = false;
      try {
        const resp = await fetch("/desktop/status", { signal: AbortSignal.timeout(3000) });
        if (resp.ok) {
          const status = await resp.json();
          running = status?.running === true;
        }
      } catch { /* status probe is best-effort */ }
      const data = await loadBalance(undefined);
      if (!alive) return;
      const providers = data?.providers;
      const healthy = Array.isArray(providers)
        && providers.some((p) => p.configured && !p.error);
      if (running) {
        schedule(5000);
      } else if (prevRunning) {
        schedule(5000);
      } else if (!healthy) {
        schedule(5000);
      } else {
        schedule(60000);
      }
      prevRunning = running;
    };
    tick();
    return () => {
      alive = false;
      window.clearTimeout(timer);
    };
  }, [loadBalance]);

  // follow the current session's model selection so the card tracks the
  // platform in use (DeepSeek model → balance; gateway model → usage)
  const sessionsSnap = react.useSyncExternalStore(
    (fn) => (sessions?.list?.subscribe ?? noopSub)(fn),
    () => sessions?.list?.getSnapshot?.() ?? null,
  );
  const sessionId = sessionsSnap?.current ?? null;
  const [directory, setDirectory] = react.useState(null);
  react.useEffect(() => {
    if (!sessionId) { setDirectory(null); return; }
    let dir = null;
    try { dir = modelDirectories?.directoryFor?.(sessionId) ?? null; } catch { dir = null; }
    setDirectory(dir);
  }, [sessionId, modelDirectories]);
  const dirSnap = react.useSyncExternalStore(
    (fn) => (directory?.subscribe ?? noopSub)(fn),
    () => directory?.getSnapshot?.() ?? null,
  );
  const selection = dirSnap?.current ?? null;

  const providers = balance?.providers ?? null;
  const active = activeProvider(providers, selection);
  const amount = providers === null
    // legacy shell without multi-provider payload
    ? (() => {
      const info = balance?.balance?.balance_infos?.[0];
      if (!balance || !info || !balance.configured) return null;
      if (balance.balance.is_available !== false) return `${info.total_balance} ${info.currency ?? ""}`.trim();
      return null;
    })()
    : providerAmount(active);
  const low = balance?.low === true && (active === null || active.kind === "balance");
  const off = providers === null
    ? (!balance || balance.configured === false)
    : !providers.some((p) => p.configured);
  const amountLabel = active !== null && active.kind === "usage" ? t("badge.usage") : t("badge");

  return jsxs(Fragment, { children: [
    jsx(primitives.Tooltip, {
      label: error ? t("badge.offline") : amount !== null ? `${amountLabel}: ${amount}` : off ? t("badge.unconfigured") : amountLabel,
      delayMs: 500,
      disabled: wide,
      children: jsx("button", {
        type: "button",
        className: "dbb_trigger" + (wide ? "" : " dbb_rail"),
        "aria-haspopup": "dialog",
        "aria-expanded": open,
        onClick: () => { setOpen((v) => !v); },
        children: wide
          ? [
            jsx("span", { className: "dbb_avatar", children: jsx(primitives.FishLogo, { size: 14 }) }),
            jsx("span", { className: "dbb_label", children: amountLabel }),
            jsx("span", {
              className: "dbb_amount" + (low ? " dbb_low" : "") + (off ? " dbb_off" : "") + (error ? " dbb_err" : ""),
              children: error ? "—" : amount !== null ? amount : off ? t("badge.unconfigured") : "—",
            })
          ]
          : [
            jsx("span", { className: "dbb_icon", children: jsx(primitives.FishLogo, { size: 18 }) })
          ]
      })
    }),
    open && jsx(BalancePanel, {
      t,
      balance,
      error,
      loadBalance,
      onClose: () => { setOpen(false); },
    })
  ] });
}

module.exports = { noopSub, activeProvider, providerAmount, BalanceBadge };

},
"./balance-panel.js": function (require, module, exports) {
// dsh-desktop-bridge — balance/usage panel.
//
// Split into a stateful wrapper (BalancePanel: usage loading, Escape /
// outside-click dismissal, refresh) and a pure view (BalancePanelView) that
// renders whatever data the wrapper holds. The view is exported for
// fixture-driven tests; every render branch below is a verbatim move from the
// pre-split bundle.
const react = require('react');
const { jsx, jsxs, Fragment } = require('react/jsx-runtime');
const primitives = require('@deepseek-ai/dsh-client-ui-primitives');
const { fmtTokens, fmtMoney, fmtUsd, fmtDate, estimateCost } = require('./helpers.js');

/** Pure render layer: props in, panel markup out (no fetch, no effects). */
function BalancePanelView(props) {
  const { t, balance, error, usage, usageError, refreshing, onRefresh, onClose, panelRef } = props;

  const providers = balance?.providers ?? null;
  const legacyInfo = balance?.balance?.balance_infos?.[0];
  const legacyTotal = legacyInfo?.total_balance ?? null;
  const legacyCurrency = legacyInfo?.currency ?? "";
  const legacyBadge = !balance || balance.configured === false
    ? jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("balance.none") })
    : balance.balance?.is_available === false
      ? jsx("span", { className: "dbb_badge dbb_badgeErr", children: t("balance.unavailable") })
      : balance.low === true
        ? jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("balance.low") })
        : jsx("span", { className: "dbb_badge dbb_badgeOk", children: t("balance.ok") });

  const providerBadge = (p) => {
    if (!p.configured) return jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("badge.unconfigured") });
    if (p.kind === "unsupported") return jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("balance.unsupported") });
    if (p.error) return jsx("span", { className: "dbb_badge dbb_badgeErr", children: t("badge.offline") });
    if (p.kind === "balance") {
      if (p.balance?.is_available === false) return jsx("span", { className: "dbb_badge dbb_badgeErr", children: t("balance.unavailable") });
      if (balance?.low === true) return jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("balance.low") });
      return jsx("span", { className: "dbb_badge dbb_badgeOk", children: t("balance.ok") });
    }
    if (p.usage) return jsx("span", { className: "dbb_badge dbb_badgeOk", children: t("balance.ok") });
    return jsx("span", { className: "dbb_badge dbb_badgeWarn", children: t("balance.none") });
  };

  const providerCard = (p) => {
    const info = p.kind === "balance" ? p.balance?.balance_infos?.[0] : null;
    const usageData = p.kind === "usage" ? p.usage : null;
    const unsupported = p.kind === "unsupported";
    const big = p.kind === "balance"
      ? info?.total_balance ?? "—"
      : Number.isFinite(usageData?.total_usage_usd) ? `$${usageData.total_usage_usd.toFixed(2)}` : "—";
    const cur = p.kind === "balance" ? info?.currency ?? "" : "USD";
    return jsxs("section", { className: "dbb_card", children: [
      jsxs("div", { className: "dbb_providerHead", children: [
        jsx("span", { className: "dbb_providerName", children: p.display_name }),
        providerBadge(p)
      ] }),
      !unsupported && jsxs("div", { className: "dbb_balanceTop", children: [
        jsx("span", { className: "dbb_balanceBig", children: big }),
        cur !== "" && jsx("span", { className: "dbb_currency", children: cur })
      ] }),
      unsupported && jsx("div", { className: "dbb_note", children: t("balance.unsupportedNote") }),
      p.kind === "balance" && info && jsxs("div", { className: "dbb_balanceSub", children: [
        jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("balance.topped"), " ", jsx("b", { children: info.topped_up_balance ?? "—" })] }) }),
        jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("balance.granted"), " ", jsx("b", { children: info.granted_balance ?? "—" })] }) })
      ] }),
      p.kind === "usage" && usageData && jsxs(Fragment, { children: [
        jsxs("div", { className: "dbb_balanceSub", children: [
          jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("usage.softLimit"), " ", jsx("b", { children: fmtUsd(usageData.soft_limit_usd) })] }) }),
          jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("usage.hardLimit"), " ", jsx("b", { children: fmtUsd(usageData.hard_limit_usd) })] }) }),
          jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("usage.payment"), " ", jsx("b", { children: usageData.has_payment_method === true ? t("usage.paymentYes") : usageData.has_payment_method === false ? t("usage.paymentNo") : "—" })] }) })
        ] }),
        jsx("div", { className: "dbb_note", children: t("balance.usageNote") })
      ] }),
      p.error && jsx("div", { className: "dbb_error", children: p.error })
    ] }, p.id);
  };

  const maxDay = usage?.byDay?.reduce((m, d) => Math.max(m, d.total), 0) ?? 0;
  const bars = (usage?.byDay ?? []).map((d, i) => {
    const h = maxDay > 0 ? Math.max(d.total > 0 ? 3 : 1.5, 54 * (d.total / maxDay)) : 1.5;
    return {
      x: i * 26 + 2,
      w: 20,
      h,
      y: 62 - h,
      title: `${d.date} · ${fmtTokens(d.total)} tokens`,
    };
  });
  const topModels = (usage?.byModel ?? []).slice(0, 6);
  const maxModel = topModels.reduce((m, r) => Math.max(m, r.tokens.total), 0);
  const topSessions = (usage?.sessions ?? []).slice(0, 6);

  return jsx("section", {
    ref: panelRef,
    className: "dbb_panel",
    "aria-label": t("panel.title"),
    children: jsxs(Fragment, { children: [
      jsxs("header", { className: "dbb_header", children: [
        jsxs("div", { className: "dbb_titleWrap", children: [
          jsxs("div", { className: "dbb_title", children: [
            jsx("span", { className: "dbb_icon", children: jsx(primitives.FishLogo, { size: 16 }) }),
            t("panel.title")
          ] }),
          jsx("div", { className: "dbb_subtitle", children: balance?.registeredAt
            ? `${t("registeredAt")} ${fmtDate(balance.registeredAt)}`
            : t("registeredAt.none") })
        ] }),
        jsxs("div", { className: "dbb_actions", children: [
          jsx("button", {
            type: "button",
            className: "dbb_iconBtn",
            "aria-label": t("panel.refresh"),
            disabled: refreshing,
            onClick: onRefresh,
            children: jsx(primitives.IconRefreshOutline14, { size: 14, className: refreshing ? "dbb_spin" : void 0 })
          }),
          jsx("button", {
            type: "button",
            className: "dbb_iconBtn",
            "aria-label": t("panel.close"),
            onClick: onClose,
            children: jsx(primitives.IconCloseOutline16, { size: 14 })
          })
        ] })
      ] }),
      jsxs("div", { className: "dbb_body", children: [
        providers === null
          ? jsxs("section", { className: "dbb_card", children: [
            jsxs("div", { className: "dbb_balanceTop", children: [
              jsx("span", { className: "dbb_balanceBig", children: legacyTotal ?? "—" }),
              legacyCurrency !== "" && jsx("span", { className: "dbb_currency", children: legacyCurrency }),
              legacyBadge
            ] }),
            legacyInfo && jsxs("div", { className: "dbb_balanceSub", children: [
              jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("balance.topped"), " ", jsx("b", { children: legacyInfo.topped_up_balance ?? "—" })] }) }),
              jsx("span", { className: "dbb_kv", children: jsxs(Fragment, { children: [t("balance.granted"), " ", jsx("b", { children: legacyInfo.granted_balance ?? "—" })] }) })
            ] }),
            error && jsx("div", { className: "dbb_error", children: t("badge.offline") })
          ] })
          : providers.map(providerCard),
        jsx("div", { className: "dbb_secTitle", children: t("usage.title") }),
        usageError
          ? jsx("div", { className: "dbb_error", children: t("usage.error") })
          : usage === null
            ? jsx("div", { className: "dbb_empty", children: t("usage.empty") })
            : usage.counts.sessions === 0
              ? jsx("div", { className: "dbb_empty", children: t("usage.empty") })
              : jsxs(Fragment, { children: [
                jsxs("div", { className: "dbb_grid", children: [
                  jsxs("div", { className: "dbb_stat", children: [
                    jsx("span", { className: "dbb_statLabel", children: t("usage.total") }),
                    jsx("span", { className: "dbb_statValue", children: fmtTokens(usage.totals.total) })
                  ] }),
                  jsxs("div", { className: "dbb_stat", children: [
                    jsx("span", { className: "dbb_statLabel", children: t("usage.input") }),
                    jsx("span", { className: "dbb_statValue", children: fmtTokens(usage.totals.input) })
                  ] }),
                  jsxs("div", { className: "dbb_stat", children: [
                    jsx("span", { className: "dbb_statLabel", children: t("usage.cacheRead") }),
                    jsx("span", { className: "dbb_statValue", children: fmtTokens(usage.totals.cacheRead) })
                  ] }),
                  jsxs("div", { className: "dbb_stat", children: [
                    jsx("span", { className: "dbb_statLabel", children: t("usage.output") }),
                    jsx("span", { className: "dbb_statValue", children: fmtTokens(usage.totals.output) })
                  ] })
                ] }),
                jsxs("div", { className: "dbb_card", children: [
                  jsxs("div", { className: "dbb_row", children: [
                    jsx("span", { className: "dbb_rowLabel", children: t("usage.cost") }),
                    jsx("span", { className: "dbb_rowValue", children: fmtMoney(estimateCost(usage)) })
                  ] }),
                  jsxs("div", { className: "dbb_row", children: [
                    jsx("span", { className: "dbb_rowLabel", children: t("usage.sessionsCount", { count: usage.counts.sessions, days: usage.counts.activeDays }) }),
                    jsx("span", { className: "dbb_rowValue", children: usage.fromAllTime ? "—" : "" })
                  ] }),
                  jsx("div", { className: "dbb_note", children: t("usage.costNote") })
                ] }),
                topModels.length > 0 && jsxs(Fragment, { children: [
                  jsx("div", { className: "dbb_secTitle", children: t("usage.models") }),
                  jsxs("div", { children: [
                    topModels.map((row) => jsxs("div", { className: "dbb_modelRow", children: [
                      jsxs("div", { className: "dbb_row", children: [
                        jsx("span", { className: "dbb_rowLabel", children: row.model }),
                        jsx("span", { className: "dbb_rowValue", children: fmtTokens(row.tokens.total) })
                      ] }),
                      jsx("div", { className: "dbb_barTrack", children: jsx("div", {
                        className: "dbb_barFill",
                        style: { width: maxModel > 0 ? `${Math.max(2, 100 * row.tokens.total / maxModel)}%` : "0%" }
                      }) })
                    ] }, row.model))
                  ] })
                ] }),
                jsx("div", { className: "dbb_secTitle", children: t("usage.days") }),
                jsxs("svg", {
                  className: "dbb_chart",
                  viewBox: "0 0 364 66",
                  role: "img",
                  "aria-label": t("usage.days"),
                  children: [
                    bars.map((bar) => jsx("rect", {
                      className: "dbb_bar",
                      x: bar.x,
                      y: bar.y,
                      width: bar.w,
                      height: bar.h,
                      rx: 3,
                      children: jsx("title", { children: bar.title })
                    }, bar.title)),
                    jsx("line", {
                      x1: 0, x2: 364, y1: 62, y2: 62,
                      stroke: "var(--dsw-alias-border-l2)",
                      strokeWidth: 1
                    })
                  ]
                }),
                topSessions.length > 0 && jsxs(Fragment, { children: [
                  jsx("div", { className: "dbb_secTitle", children: t("usage.sessions") }),
                  jsxs("div", { children: [
                    topSessions.map((s) => jsxs("div", { className: "dbb_session", children: [
                      jsxs("div", { className: "dbb_sessionTop", children: [
                        jsx("span", { className: "dbb_sessionTitle", children: s.title || t("session.untitled") }),
                        jsx("span", { className: "dbb_sessionTokens", children: fmtTokens(s.tokens.total) })
                      ] }),
                      jsx("span", { className: "dbb_sessionMeta", children: `${fmtDate(s.createdAt)} · ${s.model ?? t("session.unknown")}${typeof s.turns === "number" ? ` · ${t("turns", { count: s.turns })}` : ""}` })
                    ] }, s.id))
                  ] })
                ] })
              ] })
      ] })
    ] })
  });
}

/** Stateful wrapper: usage loading, dismissal wiring, refresh. */
function BalancePanel(props) {
  const { t, balance, error, loadBalance, onClose } = props;
  const [usage, setUsage] = react.useState(null);
  const [usageError, setUsageError] = react.useState(false);
  const [refreshing, setRefreshing] = react.useState(false);
  const panelRef = react.useRef(null);

  const loadUsage = react.useCallback(async (registeredAt) => {
    try {
      const since = typeof registeredAt === "number" ? registeredAt : 0;
      const resp = await fetch("/desktop/usage" + (since > 0 ? `?since=${since}` : ""));
      if (!resp.ok) throw new Error("http " + resp.status);
      const data = await resp.json();
      if (data?.ok !== true) throw new Error(data?.error ?? "usage error");
      setUsage(data);
      setUsageError(false);
    } catch {
      setUsageError(true);
    }
  }, []);

  react.useEffect(() => {
    loadUsage(balance?.registeredAt);
  }, [loadUsage, balance?.registeredAt]);

  react.useEffect(() => {
    const onKeyDown = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKeyDown);
    return () => { document.removeEventListener("keydown", onKeyDown); };
  }, [onClose]);

  react.useEffect(() => {
    const onPointerDown = (e) => {
      // let the trigger's own toggle own clicks on it
      if (e.target instanceof Element && e.target.closest(".dbb_trigger") !== null) return;
      if (panelRef.current !== null && !panelRef.current.contains(e.target)) onClose();
    };
    document.addEventListener("pointerdown", onPointerDown);
    return () => { document.removeEventListener("pointerdown", onPointerDown); };
  }, [onClose]);

  const refresh = async () => {
    if (refreshing) return;
    setRefreshing(true);
    try {
      const resp = await fetch("/desktop/refresh");
      if (resp.ok) {
        const data = await resp.json();
        if (data?.ok === true && data.configured !== undefined) {
          // also re-read usage against the fresh registration window
          loadUsage(data.registeredAt);
        }
      }
      await loadBalance(undefined);
    } catch { /* keep stale data */ }
    finally { setRefreshing(false); }
  };

  return jsx(BalancePanelView, {
    t,
    balance,
    error,
    usage,
    usageError,
    refreshing,
    onRefresh: refresh,
    onClose,
    panelRef,
  });
}

module.exports = { BalancePanel, BalancePanelView };

},
"./about-section.js": function (require, module, exports) {
// dsh-desktop-bridge — 关于 (About) settings section.
//
// Registered as a native settings page (`settings.section`, id "about", last
// in the nav rail): shows the desktop shell identity (author / blog / repo)
// with one-click links into the system default browser and a check-update
// action. Data comes from the shell through the bridge's same-origin
// /desktop/* proxy (shell listener → /about, /update-status, /open-external),
// so no cross-origin call from the remote dsh page is ever made.
const react = require('react');
const { jsx, jsxs, Fragment } = require('react/jsx-runtime');
const primitives = require('@deepseek-ai/dsh-client-ui-primitives');
const { ensureStyles } = require('./styles.js');

const BLOG_URL = 'https://www.anixuil.top';
const REPO_URL = 'https://github.com/Anixuil/dsh-desktop';

/** GET/POST one /desktop/* route with the { ok, ... } shell envelope. */
async function getJson(path, init) {
  const resp = await fetch(path, init);
  const payload = await resp.json().catch(() => ({}));
  if (!resp.ok || payload?.ok !== true) {
    throw new Error(payload?.error ?? `HTTP ${String(resp.status)}`);
  }
  return payload;
}

/** Pure render layer: props in, section markup out (no fetch, no effects). */
function AboutSectionView(props) {
  const { t, info, loadError, update, busy, notice, onOpen, onCheck } = props;
  const u = update?.status ?? null;

  const parts = [];
  if (u?.appUpdateAvailable === true) parts.push(t('about.appUpdate', { version: u.appLatest ?? '?' }));
  if (u?.dshUpdateAvailable === true) parts.push(t('about.dshUpdate', { version: u.dshLatest ?? '?' }));
  const updateText = update?.checking === true
    ? t('about.checking')
    : update?.error !== undefined && update?.error !== null
      ? update.error
      : u === null
        ? null
        : parts.length > 0
          ? parts.join('；')
          : t('about.latest');

  return jsxs('section', {
    className: 'dbb_about',
    'aria-label': t('about.title'),
    children: [
      jsx('h2', { className: 'dbb_aboutTitle', children: t('about.title') }),
      jsx('p', { className: 'dbb_aboutIntro', children: t('about.intro') }),
      loadError !== null
        ? jsx('p', { className: 'dbb_error', children: `${t('about.offline')}（${loadError}）` })
        : null,
      jsxs('div', { className: 'dbb_aboutCard', children: [
        jsxs('div', { className: 'dbb_aboutHead', children: [
          jsx('span', { className: 'dbb_aboutLogo', children: jsx(primitives.FishLogo, { size: 22 }) }),
          jsxs('div', { className: 'dbb_aboutTitleWrap', children: [
            jsx('div', { className: 'dbb_aboutName', children: info?.appName ?? 'DSH Desktop' }),
            info?.appVersion != null
              ? jsx('div', { className: 'dbb_aboutVer', children: t('about.version', { version: `v${info.appVersion}` }) })
              : null,
          ] }),
        ] }),
        jsxs('div', { className: 'dbb_aboutRows', children: [
          jsxs('div', { className: 'dbb_row', children: [
            jsx('span', { className: 'dbb_rowLabel', children: t('about.author') }),
            jsx('span', { className: 'dbb_rowValue', children: info?.author ?? 'Anixuil' }),
          ] }),
          info?.dshVersion != null
            ? jsxs('div', { className: 'dbb_row', children: [
                jsx('span', { className: 'dbb_rowLabel', children: t('about.dshVersion') }),
                jsx('span', { className: 'dbb_rowValue', children: info.dshVersion }),
              ] })
            : null,
          jsxs('div', { className: 'dbb_row', children: [
            jsx('span', { className: 'dbb_rowLabel', children: t('about.blog') }),
            jsx('button', {
              type: 'button',
              className: 'dbb_aboutLink',
              onClick: () => onOpen(info?.blog ?? BLOG_URL),
              children: 'www.anixuil.top',
            }),
          ] }),
          jsxs('div', { className: 'dbb_row', children: [
            jsx('span', { className: 'dbb_rowLabel', children: t('about.repo') }),
            jsx('button', {
              type: 'button',
              className: 'dbb_aboutLink',
              onClick: () => onOpen(info?.repo ?? REPO_URL),
              children: 'github.com/Anixuil/dsh-desktop',
            }),
          ] }),
        ] }),
        jsx('p', { className: 'dbb_note', children: t('about.note') }),
        jsxs('div', { className: 'dbb_aboutActions', children: [
          jsx('button', {
            type: 'button',
            className: 'dbb_aboutPrimary',
            disabled: busy,
            onClick: onCheck,
            children: busy ? t('about.checking') : t('about.check'),
          }),
          jsx('button', {
            type: 'button',
            className: 'dbb_aboutSecondary',
            onClick: () => onOpen(info?.repo ?? REPO_URL),
            children: t('about.repoBtn'),
          }),
        ] }),
        u?.appUpdateAvailable === true && u?.appUrl
          ? jsx('button', {
              type: 'button',
              className: 'dbb_aboutLink dbb_aboutRelease',
              onClick: () => onOpen(u.appUrl),
              children: t('about.release'),
            })
          : null,
        updateText !== null
          ? jsx('p', {
              className: update?.error !== undefined && update?.error !== null ? 'dbb_error' : 'dbb_aboutStatus',
              children: updateText,
            })
          : null,
        notice?.kind === 'err'
          ? jsx('p', { className: 'dbb_error', children: notice.text })
          : null,
      ] }),
    ],
  });
}

/** Stateful wrapper: loads /desktop/about once, drives update checks and link opens. */
function AboutSection(props) {
  const { t } = props;
  const [info, setInfo] = react.useState(null);
  const [loadError, setLoadError] = react.useState(null);
  const [update, setUpdate] = react.useState(null);
  const [busy, setBusy] = react.useState(false);
  const [notice, setNotice] = react.useState(null);

  react.useEffect(() => {
    ensureStyles();
    let cancelled = false;
    getJson('/desktop/about')
      .then((payload) => {
        if (cancelled) return;
        setInfo(payload);
        setLoadError(null);
      })
      .catch((e) => {
        if (!cancelled) setLoadError(String(e?.message ?? e));
      });
    return () => { cancelled = true; };
  }, []);

  const openExternal = async (url) => {
    if (!url) return;
    setNotice(null);
    try {
      await getJson('/desktop/open-external', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ url }),
      });
    } catch (e) {
      setNotice({ kind: 'err', text: String(e?.message ?? e) });
    }
  };

  const checkUpdate = async () => {
    if (busy) return;
    setBusy(true);
    setUpdate({ checking: true });
    try {
      const payload = await getJson('/desktop/update-status');
      setUpdate({ checking: false, status: payload });
    } catch (e) {
      setUpdate({ checking: false, error: String(e?.message ?? e) });
    } finally {
      setBusy(false);
    }
  };

  return jsx(AboutSectionView, {
    t,
    info,
    loadError,
    update,
    busy,
    notice,
    onOpen: openExternal,
    onCheck: checkUpdate,
  });
}

module.exports = { AboutSection, AboutSectionView };

},
"./index.js": function (require, module, exports) {
// dsh-desktop-bridge — web client module entry.
//
// Registered into the sidebar footer (list slot, order 100): the account /
// usage badge and its panel. Also registers the 关于 (About) page into the
// in-app settings modal (`settings.section`, id "about", order 30 — last in
// the nav rail). Implementation lives in the modules under src/: styles
// (load-time stylesheet), helpers (formatting + cost estimate), locales
// (desktop-balance dictionaries), balance-badge (footer trigger),
// balance-panel (panel host + pure view), about-section (shell identity +
// check-update page).
require('./styles.js');
const { BalanceBadge } = require('./balance-badge.js');
const { BalancePanelView } = require('./balance-panel.js');
const { AboutSection, AboutSectionView } = require('./about-section.js');
const { zh, en, NS } = require('./locales.js');

/** Services required from the client root context. */
const inject = ["slots", "locale"];

function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), "dsh-desktop-bridge: dictionaries");
  const t = ctx.locale.bind(NS);
  ctx.slots.inject("sidebar.footer.action", () => ctx.slots.register({
    name: "sidebar.footer.action",
    id: "desktop-balance",
    order: 100,
    locale: NS,
    inject: () => ({
      t,
      // follow the current session's model selection so the card shows
      // the platform actually in use (resolved lazily, both optional)
      sessions: ctx.get?.("sessions") ?? null,
      modelDirectories: ctx.get?.("modelDirectories") ?? null,
    })
  }, BalanceBadge));
  // 关于 (About) page in the in-app settings modal: shell identity, blog /
  // repo links into the default browser, and a shell+dsh check-update action.
  ctx.slots.inject("settings.section", () => ctx.slots.register({
    name: "settings.section",
    id: "about",
    order: 30,
    label: () => t("about.nav"),
    inject: () => ({ t }),
  }, AboutSection));
}

exports.apply = apply;
exports.inject = inject;
// Pure view + helpers re-exported for fixture-driven tests and future
// in-browser consumers (the pre-split bundle exposed nothing but apply).
exports.views = { BalancePanelView, AboutSectionView };

}
		};
		var __cache = {};
		var __require = (spec) => {
			if (spec.startsWith(".")) {
				var cached = __cache[spec];
				if (cached !== undefined) return cached.exports;
				var factory = __modules[spec];
				if (factory === undefined) throw new Error("dsh-desktop-bridge" + ": unresolved module " + spec);
				var module = { exports: {} };
				__cache[spec] = module;
				factory(__require, module, module.exports);
				return module.exports;
			}
			return require(spec);
		};
		return __require("./index.js");
	}
});
