// dsh-desktop-conversation-navigator client bundle — GENERATED by scripts/lib/build-client-bundle.mjs, do not edit.
// Modular source lives in src/; this file is the deployed artifact.
window.__ModuleLoader__.load({
	id: "dsh-desktop-conversation-navigator",
	factory: (require) => {
		var __modules = {
"./model.js": function (require, module, exports) {
// Pure conversation projection helpers. They intentionally consume only the
// public session snapshot shape so the navigator stays independent of DOM text.

function normalizeText(value) {
  if (typeof value !== 'string') return ''
  return value
    .replace(/```[^\n]*\n?/g, ' ')
    .replace(/```/g, ' ')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/^\s{0,3}(?:#{1,6}|>|[-+*]|\d+[.)])\s+/gm, '')
    .replace(/[\t\r ]+/g, ' ')
    .replace(/\n{2,}/g, '\n')
    .trim()
}

function firstParagraph(value) {
  const normalized = normalizeText(value)
  if (normalized === '') return ''
  return normalized.split('\n').map((line) => line.trim()).find(Boolean) ?? ''
}

function contentText(content) {
  if (!Array.isArray(content)) return ''
  const parts = []
  for (const block of content) {
    if (block === null || typeof block !== 'object') continue
    if (typeof block.text === 'string') parts.push(block.text)
    else if (typeof block.content === 'string') parts.push(block.content)
  }
  return normalizeText(parts.join('\n'))
}

function assistantText(blocks) {
  if (!Array.isArray(blocks)) return ''
  return normalizeText(blocks
    .filter((block) => block?.kind === 'text' && typeof block.text === 'string')
    .map((block) => block.text)
    .join('\n'))
}

function turnOf(node) {
  const location = node?.location
  if (location?.kind === 'turn') return location.turn?.turn
  if (location?.kind === 'step') return location.turn?.turn
  return undefined
}

function buildTurnEntries(snapshot, copy = {}) {
  const chat = snapshot?.chat
  if (!chat || !Array.isArray(chat.order) || typeof chat.nodes?.get !== 'function') return []

  const byTurn = new Map()
  for (const key of chat.order) {
    const node = chat.nodes.get(key)
    if (!node || node.visibility === 'hidden') continue
    const turn = turnOf(node)
    if (!Number.isFinite(turn)) continue
    let entry = byTurn.get(turn)
    if (!entry) {
      entry = {
        turn,
        anchorKey: key,
        title: '',
        summary: '',
        running: false,
      }
      byTurn.set(turn, entry)
    }

    const data = node.data ?? {}
    if ((node.kind === 'user' || node.kind === 'steering') && entry.title === '') {
      entry.anchorKey = key
      entry.title = firstParagraph(contentText(data.content))
      if (entry.title === '' && Array.isArray(data.content) && data.content.length > 0) {
        entry.title = copy.imageMessage ?? '图片消息'
      }
    }
    if (node.kind === 'assistant-step') {
      const text = firstParagraph(assistantText(data.blocks))
      if (text !== '') entry.summary = text
      if (data.status === 'running') entry.running = true
    }
  }

  const entries = [...byTurn.values()].sort((left, right) => left.turn - right.turn)
  return entries.map((entry, index) => ({
    ...entry,
    index,
    title: entry.title || (typeof copy.turnFallback === 'function'
      ? copy.turnFallback(entry.turn)
      : (copy.turnFallback ?? '第 {turn} 轮对话').replace('{turn}', String(entry.turn))),
    summary: entry.summary || (entry.running
      ? copy.generating ?? '正在生成回复'
      : copy.noReply ?? '这一轮暂无可预览的回复'),
  }))
}

module.exports = {
  normalizeText,
  firstParagraph,
  contentText,
  assistantText,
  turnOf,
  buildTurnEntries,
}

},
"./locales.js": function (require, module, exports) {
const zh = {
  navLabel: '对话导航',
  turnLabel: '第 {turn} 轮：{title}',
  turnFallback: '第 {turn} 轮对话',
  imageMessage: '图片消息',
  generating: '正在生成回复',
  noReply: '这一轮暂无可预览的回复',
  loadOlder: '加载更早的对话',
  loadingOlder: '正在加载更早的对话',
}

const en = {
  navLabel: 'Conversation navigator',
  turnLabel: 'Turn {turn}: {title}',
  turnFallback: 'Conversation turn {turn}',
  imageMessage: 'Image message',
  generating: 'Generating a response',
  noReply: 'No response preview is available for this turn',
  loadOlder: 'Load earlier conversation',
  loadingOlder: 'Loading earlier conversation',
}

module.exports = { zh, en }

},
"./styles.js": function (require, module, exports) {
const STYLE_ID = 'dsh-desktop-conversation-navigator-styles'

function ensureStyles() {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID) !== null) return
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.dataset.plugin = 'dsh-desktop-conversation-navigator'
  style.textContent = `
.dcn_root{box-sizing:border-box;width:28px;position:absolute;z-index:9;pointer-events:auto}
.dcn_scroller{box-sizing:border-box;width:28px;height:100%;padding:2px 0;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:none}
.dcn_scroller::-webkit-scrollbar{display:none}
.dcn_list{list-style:none;width:28px;min-height:100%;margin:0;padding:0;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:2px}
.dcn_item{width:28px;height:18px;margin:0;padding:0;display:flex;align-items:center;justify-content:flex-start}
.dcn_tick{box-sizing:border-box;width:28px;height:18px;margin:0;padding:0;border:0;border-radius:5px;background:transparent;color:var(--dsw-alias-label-caption);cursor:pointer;display:flex;align-items:center;justify-content:flex-start}
.dcn_tickLine{display:block;width:12px;height:1.5px;border-radius:2px;background:currentColor;opacity:.62;transform-origin:left center;transition:width .12s cubic-bezier(.16,1,.3,1),height .12s cubic-bezier(.16,1,.3,1),opacity .12s ease,color .12s ease}
.dcn_tick:hover{color:var(--dsw-alias-label-secondary)}
.dcn_tick:hover .dcn_tickLine,.dcn_tick:focus-visible .dcn_tickLine{width:18px;opacity:1}
.dcn_tick[aria-current=location]{color:var(--dsw-alias-state-business-primary)}
.dcn_tick[aria-current=location] .dcn_tickLine{width:22px;height:2px;opacity:1}
.dcn_tick:focus-visible{outline:1.5px solid var(--dsw-alias-button-info-fill);outline-offset:1px}
.dcn_tick:active .dcn_tickLine{transform:scaleX(.92)}
.dcn_load{color:var(--dsw-alias-label-tertiary)}
.dcn_load .dcn_tickLine{width:8px;box-shadow:0 -4px 0 currentColor,0 4px 0 currentColor}
.dcn_load:disabled{cursor:default;opacity:.46}
.dcn_preview{box-sizing:border-box;width:min(320px,calc(100vw - 56px));padding:10px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);box-shadow:var(--dsw-shadow-lv2);pointer-events:none;position:absolute;left:34px;opacity:1;transform:translateY(0);transition:opacity .12s ease,transform .12s cubic-bezier(.16,1,.3,1)}
.dcn_previewTitle{font:var(--dsw-font-s-strong-14);white-space:nowrap;text-overflow:ellipsis;overflow:hidden}
.dcn_previewSummary{color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:19px;margin-top:4px;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;overflow-wrap:anywhere}
@media (prefers-reduced-motion:reduce){.dcn_tickLine,.dcn_preview{transition:none}.dcn_tick:active .dcn_tickLine{transform:none}}
`
  document.head.appendChild(style)
}

module.exports = { ensureStyles, STYLE_ID }

},
"./navigator.js": function (require, module, exports) {
const react = require('react')
const { jsx, jsxs } = require('react/jsx-runtime')
const { buildTurnEntries } = require('./model.js')
const { ensureStyles } = require('./styles.js')

const EMPTY_SNAPSHOT = Object.freeze({
  chat: { order: [], nodes: { get: () => undefined } },
  hasMore: false,
  loadingOlder: false,
  running: false,
})
const EMPTY_STORE = Object.freeze({
  getSnapshot: () => EMPTY_SNAPSHOT,
  subscribe: () => () => {},
})

function findAnchor(key) {
  if (typeof document === 'undefined') return null
  for (const node of document.querySelectorAll('[data-chat-anchor-key]')) {
    if (node.dataset.chatAnchorKey === key) return node
  }
  return null
}

function computeLayout(rects) {
  if (!rects?.overlay || !rects.sidebar || !rects.flow || !rects.scroll) return null
  const top = rects.scroll.top + 14
  const visibleBottom = Math.min(rects.scroll.bottom, rects.composer?.top ?? rects.scroll.bottom) - 14
  const height = Math.floor(visibleBottom - top)
  if (height < 72) return null
  const sidebarLeft = rects.sidebar.right + 12
  const contentSafeLeft = rects.flow.left - 34
  const left = Math.max(rects.scroll.left + 4, Math.min(sidebarLeft, contentSafeLeft))
  return {
    left: Math.round(left - rects.overlay.left),
    top: Math.round(top - rects.overlay.top),
    height,
  }
}

function copyFor(t) {
  return {
    imageMessage: t('imageMessage'),
    turnFallback: (turn) => t('turnFallback', { turn }),
    generating: t('generating'),
    noReply: t('noReply'),
  }
}

function ConversationNavigator({ sessions, t }) {
  const listSnapshot = react.useSyncExternalStore(
    react.useCallback((notify) => sessions?.list?.subscribe?.(notify) ?? (() => {}), [sessions]),
    react.useCallback(() => sessions?.list?.getSnapshot?.() ?? { current: null }, [sessions]),
  )
  const sessionId = listSnapshot?.current ?? null
  const session = sessionId === null ? null : sessions?.binding?.(sessionId)?.session ?? null
  const store = session ?? EMPTY_STORE
  const snapshot = react.useSyncExternalStore(
    react.useCallback((notify) => store.subscribe(notify), [store]),
    react.useCallback(() => store.getSnapshot(), [store]),
  )
  const entries = react.useMemo(() => buildTurnEntries(snapshot, copyFor(t)), [snapshot, t])
  const [layout, setLayout] = react.useState(null)
  const [activeTurn, setActiveTurn] = react.useState(null)
  const [previewTurn, setPreviewTurn] = react.useState(null)
  const [previewTop, setPreviewTop] = react.useState(0)
  const rootRef = react.useRef(null)
  const scrollerRef = react.useRef(null)
  const previewRef = react.useRef(null)
  const buttonRefs = react.useRef(new Map())

  react.useEffect(() => {
    ensureStyles()
  }, [])

  react.useLayoutEffect(() => {
    if (entries.length < 2 || typeof document === 'undefined') {
      setLayout(null)
      return undefined
    }
    const overlay = document.querySelector('[data-shell-overlay]')
    const scroll = document.querySelector('[data-conversation-scroll]')
    const sidebar = overlay?.parentElement?.firstElementChild ?? null
    if (!(overlay instanceof HTMLElement) || !(sidebar instanceof HTMLElement) || !(scroll instanceof HTMLElement)) {
      setLayout(null)
      return undefined
    }
    const observed = new Set([overlay, sidebar, scroll])
    const resizeObserver = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(() => measure())
    const observe = (element) => {
      if (!(element instanceof HTMLElement) || observed.has(element)) return
      observed.add(element)
      resizeObserver?.observe(element)
    }
    const measure = () => {
      const flow = scroll.querySelector('[data-chat-flow]')
      const composer = scroll.querySelector('[data-composer-seat]')
      if (!(flow instanceof HTMLElement)) {
        setLayout(null)
        return
      }
      observe(flow)
      observe(composer)
      setLayout(computeLayout({
        overlay: overlay.getBoundingClientRect(),
        sidebar: sidebar.getBoundingClientRect(),
        flow: flow.getBoundingClientRect(),
        scroll: scroll.getBoundingClientRect(),
        composer: composer instanceof HTMLElement ? composer.getBoundingClientRect() : null,
      }))
    }
    resizeObserver?.observe(overlay)
    resizeObserver?.observe(sidebar)
    resizeObserver?.observe(scroll)
    const mutationObserver = typeof MutationObserver === 'undefined' ? null : new MutationObserver(measure)
    mutationObserver?.observe(scroll, { childList: true, subtree: true })
    measure()
    return () => {
      resizeObserver?.disconnect()
      mutationObserver?.disconnect()
    }
  }, [sessionId, entries.length])

  react.useEffect(() => {
    if (layout === null || entries.length < 2 || typeof document === 'undefined') return undefined
    const scroll = document.querySelector('[data-conversation-scroll]')
    if (!(scroll instanceof HTMLElement)) return undefined
    const anchored = entries
      .map((entry) => ({ entry, element: findAnchor(entry.anchorKey) }))
      .filter((item) => item.element instanceof HTMLElement)
    if (anchored.length === 0) return undefined

    const activationLine = scroll.getBoundingClientRect().top + scroll.clientHeight * .28
    let initial = anchored[0]
    for (const item of anchored) {
      if (item.element.getBoundingClientRect().top <= activationLine) initial = item
      else break
    }
    setActiveTurn(initial.entry.turn)

    if (typeof IntersectionObserver === 'undefined') return undefined
    const visible = new Map()
    const turns = new Map(anchored.map(({ entry, element }) => [element, entry.turn]))
    const observer = new IntersectionObserver((changes) => {
      for (const change of changes) {
        const turn = turns.get(change.target)
        if (!Number.isFinite(turn)) continue
        if (change.isIntersecting) visible.set(turn, change.boundingClientRect.top)
        else visible.delete(turn)
      }
      if (visible.size === 0) return
      const next = [...visible].sort((left, right) => left[1] - right[1])[0]?.[0]
      if (Number.isFinite(next)) setActiveTurn(next)
    }, { root: scroll, rootMargin: '0px 0px -68% 0px', threshold: 0 })
    for (const { entry, element } of anchored) {
      observer.observe(element)
    }
    return () => observer.disconnect()
  }, [sessionId, entries, layout])

  react.useEffect(() => {
    if (activeTurn === null) return
    buttonRefs.current.get(activeTurn)?.scrollIntoView?.({ block: 'nearest' })
  }, [activeTurn])

  react.useLayoutEffect(() => {
    if (previewTurn === null || layout === null) return
    const button = buttonRefs.current.get(previewTurn)
    const scroller = scrollerRef.current
    const preview = previewRef.current
    if (!(button instanceof HTMLElement) || !(scroller instanceof HTMLElement) || !(preview instanceof HTMLElement)) return
    const desired = button.offsetTop - scroller.scrollTop - 6
    setPreviewTop(Math.max(0, Math.min(desired, layout.height - preview.offsetHeight)))
  }, [previewTurn, layout])

  const jumpTo = react.useCallback((entry) => {
    const target = findAnchor(entry.anchorKey)
    const scroll = typeof document === 'undefined' ? null : document.querySelector('[data-conversation-scroll]')
    if (!(target instanceof HTMLElement) || !(scroll instanceof HTMLElement)) return
    const top = scroll.scrollTop + target.getBoundingClientRect().top - scroll.getBoundingClientRect().top - 12
    const reduce = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches === true
    scroll.scrollTo({ top: Math.max(0, top), behavior: reduce ? 'auto' : 'smooth' })
    setActiveTurn(entry.turn)
  }, [])

  const focusRelative = react.useCallback((entry, delta) => {
    const index = entries.findIndex((candidate) => candidate.turn === entry.turn)
    const next = entries[Math.max(0, Math.min(entries.length - 1, index + delta))]
    if (next) buttonRefs.current.get(next.turn)?.focus()
  }, [entries])

  if (layout === null || entries.length < 2) return null
  const preview = entries.find((entry) => entry.turn === previewTurn) ?? null
  const previewId = preview === null ? undefined : `dcn-preview-${sessionId}-${preview.turn}`
  const previewMaxWidth = typeof window === 'undefined'
    ? 320
    : Math.max(160, Math.min(320, window.innerWidth - layout.left - 70))
  return jsxs('nav', {
    ref: rootRef,
    className: 'dcn_root',
    style: { left: layout.left, top: layout.top, height: layout.height },
    'aria-label': t('navLabel'),
    children: [
      jsx('div', { ref: scrollerRef, className: 'dcn_scroller', children: jsxs('ol', { className: 'dcn_list', children: [
        snapshot.hasMore ? jsx('li', { className: 'dcn_item', children: jsx('button', {
          type: 'button',
          className: 'dcn_tick dcn_load',
          disabled: snapshot.loadingOlder,
          'aria-label': t(snapshot.loadingOlder ? 'loadingOlder' : 'loadOlder'),
          onClick: () => session?.loadOlder?.(),
          children: jsx('span', { className: 'dcn_tickLine', 'aria-hidden': 'true' }),
        }) }, 'load-older') : null,
        ...entries.map((entry) => jsx('li', { className: 'dcn_item', children: jsx('button', {
          ref: (node) => {
            if (node === null) buttonRefs.current.delete(entry.turn)
            else buttonRefs.current.set(entry.turn, node)
          },
          type: 'button',
          className: 'dcn_tick',
          tabIndex: activeTurn === entry.turn ? 0 : -1,
          'aria-current': activeTurn === entry.turn ? 'location' : undefined,
          'aria-describedby': previewTurn === entry.turn ? previewId : undefined,
          'aria-label': t('turnLabel', { turn: entry.turn, title: entry.title }),
          onClick: () => jumpTo(entry),
          onMouseEnter: () => setPreviewTurn(entry.turn),
          onMouseLeave: () => setPreviewTurn((current) => current === entry.turn ? null : current),
          onFocus: () => setPreviewTurn(entry.turn),
          onBlur: () => setPreviewTurn((current) => current === entry.turn ? null : current),
          onKeyDown: (event) => {
            if (event.key === 'ArrowDown') { event.preventDefault(); focusRelative(entry, 1) }
            else if (event.key === 'ArrowUp') { event.preventDefault(); focusRelative(entry, -1) }
            else if (event.key === 'Home') { event.preventDefault(); buttonRefs.current.get(entries[0].turn)?.focus() }
            else if (event.key === 'End') { event.preventDefault(); buttonRefs.current.get(entries.at(-1).turn)?.focus() }
          },
          children: jsx('span', { className: 'dcn_tickLine', 'aria-hidden': 'true' }),
        }) }, entry.turn)),
      ] }) }),
      preview ? jsxs('div', { id: previewId, ref: previewRef, className: 'dcn_preview', style: { top: previewTop, maxWidth: previewMaxWidth }, role: 'tooltip', children: [
        jsx('div', { className: 'dcn_previewTitle', children: preview.title }),
        jsx('div', { className: 'dcn_previewSummary', children: preview.summary }),
      ] }) : null,
    ],
  })
}

module.exports = {
  ConversationNavigator,
  computeLayout,
  findAnchor,
  EMPTY_SNAPSHOT,
}

},
"./index.js": function (require, module, exports) {
// dsh-desktop-conversation-navigator - frame-wide local conversation outline.
const { ConversationNavigator, computeLayout } = require('./navigator.js')
const model = require('./model.js')
const { zh, en } = require('./locales.js')

const NS = 'conversationNavigator'
const inject = ['slots', 'locale', 'sessions']

function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'dsh-desktop-conversation-navigator: dictionaries')
  const t = ctx.locale.bind(NS)
  ctx.slots.inject('shell.overlay', () => ctx.slots.register({
    name: 'shell.overlay',
    id: 'conversation-navigator',
    order: 20,
    locale: NS,
    inject: () => ({ sessions: ctx.sessions, t }),
  }, ConversationNavigator))
}

exports.apply = apply
exports.inject = inject
exports.helpers = { ...model, computeLayout }
exports.views = { ConversationNavigator }

}
		};
		var __cache = {};
		var __require = (spec) => {
			if (spec.startsWith(".")) {
				var cached = __cache[spec];
				if (cached !== undefined) return cached.exports;
				var factory = __modules[spec];
				if (factory === undefined) throw new Error("dsh-desktop-conversation-navigator" + ": unresolved module " + spec);
				var module = { exports: {} };
				__cache[spec] = module;
				factory(__require, module, module.exports);
				return module.exports;
			}
			return require(spec);
		};
		return __require("./index.js");
	}
});
